### ISSUE TITLE
Banners on User Preferences Page

### ISSUE THREAD

**Issue by bruinc** [tl-its-umich-edu/remote-office-hours-queue#102]
Add banners on the User Preferences Page for:

1. Preferences have been saved (green or blue)
2. Validation failed (ErrorDisplay banner)

**Comment by jlost** [comment]
@bruinc @ssciolla Assigned this to Sam - let me know if you happen to have already started work on it.

**Comment by bruinc** [comment]
That's perfect; I have not started work on this.

**Comment by teshsopher** [comment]
@ssciolla For the most part this works, but, when the user deletes their number and leaves the field blank or leaves the "+1" extension, the banner displayed on Chrome is "Your preferences have not been saved," while, on Firefox or Safari, the banner displays "Your preferences have been saved." 

As far as I can tell (please correct me if I'm wrong!), the number remains deleted/cleared no matter the browser, so it should display that the preferences have been saved.

**Comment by ssciolla** [comment]
@teshsopher, hm, let me take a look at the cross-browser comparison. This may have something to do with a bug in the component that doesn't let you clear all the characters (see comments on #121). I tried to work around that, but I may have missed something.

**Comment by ssciolla** [comment]
@teshsopher, would you be willing to show me the behavior you're talking about? I don't think I've been able to replicate it, but that doesn't mean it's not happening. Feel free to DM me.

**Comment by teshsopher** [comment]
@ssciolla I think I may have accidentally double-clicked on the "Save" button by mistake, since I can't replicate this behavior either now. Sorry for the trouble!

**Comment by ssciolla** [comment]
No worries, let me know if you have other thoughts about this fix.

**Comment by teshsopher** [comment]
I don't see any issues. Moving this to done!
