### ISSUE TITLE
Hide Phone Field in Join Info if Nonexistent

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#104]
I noticed an attendee's phone number shows up with odd example text if the attendee hasn't added a phone number yet. We could replace this with something nicer, or simply hide the phone field altogether.

![image](https://user-images.githubusercontent.com/11338926/87475502-ea301a80-c5f2-11ea-9fcb-e7f0d267c4f0.png)

**Comment by bruinc** [comment]
Merged- closing the issue.

**Comment by teshsopher** [comment]
QA tested and working in dev on 8/12
