### ISSUE TITLE
Keep Description Field in Edit State If Error on Saving

### ISSUE THREAD

**Issue by teshsopher** [tl-its-umich-edu/remote-office-hours-queue#107]
If the number of characters in the Description field is over the limit (>1000 characters), and the host tries to save, the field is no longer in the edit state. 

The Description field should be left in the edit state to better indicate where the error happened and so that the host doesn't lose their what they've typed.

**Comment by ssciolla** [comment]
Hi @teshsopher, @mfldavidson, not sure who will review issue #111, but I may have resolved this issue also, depending on the desired behavior.

**Comment by teshsopher** [comment]
@ssciolla I tested this, and it works great!

QA tested and working in dev on 8/12

**Comment by ssciolla** [comment]
Great, @teshsopher, I'm going to close this issue.
