### ISSUE TITLE
Agenda Field - Edit State Changes

### ISSUE THREAD

**Issue by teshsopher** [tl-its-umich-edu/remote-office-hours-queue#108]
If there is an error saving the agenda (e.g. the attendee has entered an agenda with more than 100 characters), the error should display as normal, but the Agenda field should be in the edit state.

Additionally, if there is an agenda already when the page loads, the field should **not** be in the edit state.

**Comment by teshsopher** [comment]
@bruinc If possible, it would also be good to indicate the character limit like you did for the Description field on the Host's side.

**Comment by mfldavidson** [comment]
Was this resolved by your change @ssciolla ?

**Comment by ssciolla** [comment]
I don't think so, but I'll check.

**Comment by ssciolla** [comment]
@mfldavidson, are we still trying to get this in the release? I started work on this, so I could have it done today. Let me know what you think; I'm fine either way.

**Comment by mfldavidson** [comment]
Tested and working in QA
