### ISSUE TITLE
Allow Users to Remove Alternate Contact Information

### ISSUE THREAD

**Issue by teshsopher** [tl-its-umich-edu/remote-office-hours-queue#109]
Allow users to remove contact information (either by deleting the information, or having a link/text button next to the field that says 'Clear,' and let users save the blank field).

Additionally, make sure that the old number is not shown to hosts.

**Comment by bruinc** [comment]
@teshsopher I had the intention of allowing users to remove their phone number (set it to be blank), and it worked for me in testing, but while testing I always _highlighted_ the entire field with my mouse and deleted the phone number. My bad for not testing deleting the phone number by backspacing/deleting each character.

**Comment by jlost** [comment]
@teshsopher Can you take a look at the current implementation in dev and let me know if it fits the bill for this issue? You can clear the phone field and click Save to remove your phone number, although there isn't an explicit Clear button.

**Comment by teshsopher** [comment]
@jlost This looks good! I think, in a "nice to have" case, there would be a clear/remove button for the number, but it isn't necessary, based on some "hallway" user tests. The only issue that I have is that when I delete the full number (including the +1 ), it shows up with placeholder text, which may confuse some users into thinking that they have to delete that too. When I delete the entire field, this is what I see:

![image](https://user-images.githubusercontent.com/63423382/96597230-94d36b80-12bb-11eb-835b-2baa7ecfd8fe.png)

**Comment by jlost** [comment]
In that case, I can remove the placeholder entirely.

**Comment by teshsopher** [comment]
Tested and working in QA
