### ISSUE TITLE
Full email doesn't work and doesn't provide a useful message to the user

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#11]
Entering "foobar@umich.edu" no longer works for Attendees or Hosts.

-- Eric Boyd

**Comment by jzenas** [comment]
Hello, I'm an EECS 481 student and I plan to try to resolve this issue. I would like to clarify the issue. Do we want to make it so a user can enter in a umich email where the website asks for a uniqname when entering hosts and attendees or am I misunderstanding the issue?

**Comment by OscarSong2003** [comment]
Hey, is this issue resolved?  If not, I would like to look into this for EECS 481. Thanks

**Comment by jonespm** [comment]
It doesn't _look_ like anyone is working on this. It seems like a validation is blocking this. But I'm not entirely sure the fix. 

I feel like the easiest fix might be for a separate message in the [validation.ts](https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/37cceecbae64c649c9fb2c95679219af175aad35/src/assets/src/validation.ts#L66) file where if the name contains a `@` sign then to print like "You need to use a uniqname and not an email address".

I think ideally this app would support storing email addresses AND uniqnames, but I think that the single sign on currently only allows for uniqname users to login.

**Comment by OscarSong2003** [comment]
Will look into this!

**Comment by zqian** [comment]
@OscarSong2003 Still on track to fix the issue?

**Comment by OscarSong2003** [comment]
Yes, raising PR right now.

**Comment by OscarSong2003** [comment]
@zqian Just finished raising the PR. Thanks!
