### ISSUE TITLE
Temporarily remove user phone_number from API & edit page

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#112]
Because anyone can be a host and any host can look up any user's phone_number, it's effectively public. Let's make it private by not returning it from the API and removing the "alternate contact info" display on the edit page for now.  If we need to return the phone_number for the edit profile page, the phone_number field can be made to only render if the user making the request is the same as the user being requested.

The field can still be used for notifications, and we may tighten the security around who is allowed to be a host in the future, which would allow us to add the "alternate contact info" display back in. Another way we could add it back in is by removing the ability to force-add a user to a queue from the edit page. Because the user will have added themselves, they will have effectively volunteered to display their contact information.

**Comment by jlost** [comment]
@teshsopher @bruinc @mfldavidson Any thoughts?

**Comment by bruinc** [comment]
@jlost I agree with you. And I think whenever we add it back, a statement next to the phone number field on the preferences page saying who would be able to see it and when might be a good idea.

**Comment by teshsopher** [comment]
I agree that we should hide the number for now and, if/when we add it back, we do let the user who has access to their number

@jlost As far as using the number for notifications, since that's in a later milestone, should we hide the Preferences page until that is implemented?

**Comment by teshsopher** [comment]
QA tested and working in dev on 8/14
