### ISSUE TITLE
Joining the Meeting text typo

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#114]
On the join queue page, once someone is in line, they see:

> Joining the Meeting
> You can join the meeting now to make sure you are set up and ready. Download the app and test your audio before it is your turn. SeeHow to use BlueJeans at U-M for additional help getting started.

There should be a space between "See" and "How" in the last sentence. I would actually prefer we change "See" to "Refer to" since "See" implies having the ability to literally see, which not all users may have.

**Comment by teshsopher** [comment]
QA tested and visible in dev on 8/14
