### ISSUE TITLE
Adjust wording in attendee notification banners

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#115]
The yellow and green banners that notify attendees when their turn is coming up or here need some slight tweaks as we reformat the queue join page:

### Green
> It's your turn! If you haven't already joined the meeting, follow the directions on the right to join it now!

should be changed to:
> It's your turn! If you haven't already joined the meeting, follow the directions to join it now!

### Yellow
> Your turn is coming up! Follow the directions on the right to join the meeting now so you are ready when it's your turn.

should be changed to:
> Your turn is coming up! Follow the directions to join the meeting now so you are ready when it's your turn.

**Comment by teshsopher** [comment]
QA tested and working in dev on 8/17
