### ISSUE TITLE
Drop-down menu is cut off in smaller window sizes before breakpoint

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#119]
Though the drop-down menu is clearly visible in many cases, when the window size becomes small before the breakpoint, or the zoom is increased, the menu can be cut off on the right side, as in the image below.

<img width="301" alt="Screen Shot 2020-07-28 at 4 33 43 PM" src="https://user-images.githubusercontent.com/35741256/88720772-69454880-d0f3-11ea-9dc5-c814c195764a.png">

Maybe we could just have the menu open to the left instead?

**Comment by teshsopher** [comment]
In QA and in Dev, I'm still running into this issue, both when I re-size and zoom in. Here's what I'm seeing in QA:

![image](https://user-images.githubusercontent.com/63423382/92120704-619a5300-edc7-11ea-970d-614f6e063f0e.png)

**Comment by ssciolla** [comment]
Hi @teshsopher, doesn't look like this change has been pushed out to Dev and QA. I'll do that today and update you.

**Comment by mfldavidson** [comment]
Tested in Chrome and Firefox Desktop and dropdown always goes to the left now, so no possibility for getting cut off. Awesome!!! 🥇
