### ISSUE TITLE
Use websockets on /manage & remove useAutoRefresh

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#124]
One page, `/manage`, still uses `useAutoRefresh`. Switching it over to using websocket/Channels will allow us to remove `useAutoRefresh` entirely.

Doing this would necessitate a means of subscribing to the queues for which a user has been added as a host. When the user is removed or added as host to a queue, or a queue for which they're a host has been deleted, the page should update. This could be approached in a number of ways...

* Add a `hosted_queues` property to `UserSerializer` and leverage the existing `UserConsumer`. This avoids creating another consumer, and the update would need to trigger off of m2m changes and queue deletions. 
* Add a new consumer that can return queues for a particular user (or only the logged in user?). In this case, the smaller scope of results would have the benefit of simplifying the wiring of signals to consumer updates.

It would be worth considering #71 (or doing it first) because if we want to include full `hosted_queues` data in the `UserSerializer`, that might have an impact on performance (especially for `UsersConsumer`) and the depth of signals that need to be wired to consumer updates (will need to update `UserConsumer` upon hosted queue changes, not just add/remove). This could be worked around by parameterizing `UserSerializer` (pass in whether to render queue details), but it would add some complexity.

**Comment by jlost** [comment]
One other idea: We could just necessitate manual refreshes on this page by removing useAutoRefresh and otherwise leaving it as-is. I doubt users tend to linger on it or watch it for changes.

**Comment by jlost** [comment]
This will also allow `rxjs` to be removed as a dependency.

**Comment by mfldavidson** [comment]
Tested while having this page up:
- Added myself as a host to a queue (with another user)
- Removed myself as a host for a queue
- Added host again
- Opened queue
- Closed queue
- Deleted queue

All updates were super fast, no apparent issues. Nice work!!! 💯
