### ISSUE TITLE
Add breadcrumbs to Manage>Queue name to easily navigate back to manage

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#13]
From the queue page, it is difficult to navigate back to /manage. Let's add breadcrumbs to the top of the page to help them get back.

-- @mfldavidson

**Comment by jlost** [comment]
@mfldavidson @teshsopher I added this to all pages. You can see it in dev.

**Comment by mfldavidson** [comment]
This implementation looks great and makes sense to me. Would def like to hear what @teshsopher has to say to be sure. It does look a little odd to have the two gray boxes on the homepage but it's not a big deal. We could potentially get rid of the gray box around Remote Office Hours Queue and just have a white background.

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/80969986-7bf7fc00-8de8-11ea-9d4b-49e44b903e7b.png)
This is what that would look like...

**Comment by mfldavidson** [comment]
Decision: "Home" will change to a home icon and say "Remote Office Hours Queue" like on the ITS website 
![image](https://user-images.githubusercontent.com/31591389/80970672-88c91f80-8de9-11ea-99da-dc2e9893bbed.png)

Decision: go to white background on homepage behind "Remote Office Hours Queue" (i.e. no gray box to avoid confusion with the gray box for the breadcrumbs)

**Comment by jlost** [comment]
Made these changes

**Comment by mfldavidson** [comment]
Awesome! I tested it out and it looks great! @teshsopher if you test as well and approve, go ahead and move to "Done" and close it

**Comment by teshsopher** [comment]
There isn't enough color contrast between the text and the background of the breadcrumbs. Either the text should be darker or the background color should be lighter, but I don't have a strong preference either way

**Comment by jlost** [comment]
Switched to black:
![image](https://user-images.githubusercontent.com/11338926/80996295-8e386100-8e0d-11ea-848e-d9c63b114bc7.png)

**Comment by mfldavidson** [comment]
I've tried to break it every way I know how and it won't break :) I'd call this tested and good to go!
