### ISSUE TITLE
Warning Popup when Attendee clicks on "Leave the line"

### ISSUE THREAD

**Issue by teshsopher** [tl-its-umich-edu/remote-office-hours-queue#137]
In order to prevent attendees from accidentally leaving the line, there should be a warning message that pops up letting users know what will happen so they can confirm if that's what they want to do. 

Title of popup: Leave the line
Popup message: You are about to leave the line. You will lose your place in queue.

**Comment by mfldavidson** [comment]
Can this be pushed to QA @ssciolla @jlost I just tested and it isn't there

**Comment by ssciolla** [comment]
Yeah, I'll do that. Just need to re-build.

**Comment by teshsopher** [comment]
Tested and working in QA
