### ISSUE TITLE
's' on 'Manage Queues' is hidden in dropdown on smaller viewports

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#139]
If it's smaller but not so small it reverts to hamburger, the s is cut off by the scroll bar
![image](https://user-images.githubusercontent.com/31591389/90451266-6c5fa300-e0b9-11ea-9a89-2c4bcd7e75e6.png)

**Comment by ssciolla** [comment]
Possible duplicate of this? https://github.com/tl-its-umich-edu/remote-office-hours-queue/issues/119

**Comment by mfldavidson** [comment]
Oop you're right. I missed that. I will close and mark duplicate.
