### ISSUE TITLE
Add time of queue join for each person in line

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#14]
"Lost" if you will with the rewrite--I think this isn't terribly difficult and is important to show. Add "Joined queue at " just to the right of the user's name

-- @mfldavidson

**Comment by jlost** [comment]
#32

**Comment by jlost** [comment]
@teshsopher @mfldavidson 
![image](https://user-images.githubusercontent.com/11338926/80806648-40132b80-8b89-11ea-9154-74798f4bb388.png)
Thoughts?

**Comment by teshsopher** [comment]
I think this looks good, and it makes sense to have that in the "Join Info" popup on the host side, but it may be easier to skim if it is labelled "Time Joined" or "Joined Queue"

**Comment by mfldavidson** [comment]
Looks great @jlost !!! I think @teshsopher's suggestion makes sense too

**Comment by jlost** [comment]
Changed it:

**Comment by jlost** [comment]
I didn't deploy this because other changes are being looked at, but let me know if you want me to.

**Comment by teshsopher** [comment]
This is kind of a picky thing, but is it possible to modify the time to display as "Mon, May 04, 2020, 5:08:16 PM". This just makes it a little more readable in my opinion, but it's not a major problem if it can't be done.

**Comment by jlost** [comment]
Normalized date formatting throughout the app:

![image](https://user-images.githubusercontent.com/11338926/81950709-50d49000-95d2-11ea-967d-4b3e04aba551.png)

**Comment by teshsopher** [comment]
The screenshot looks good to me! I'm not seeing it in dev, however.

**Comment by jlost** [comment]
@teshsopher This is in dev now.

**Comment by teshsopher** [comment]
Looks good! Thank you!
