### ISSUE TITLE
Reconnect websockets following disconnections caused by different browsers

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#142]
Many devices disconnect websockets automatically to save power when the tab is put in the background.  When the tab returns to the foreground, check sockets and reconnect them if necessary. 

https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

Open to other suggestions!

**Comment by ssciolla** [comment]
Websocket disconnects seem to happen in a number of circumstances, though especially with Safari browsers. @jlost has proposed a more robust/predictable solution than using the visibility API in PR #147, which leverages an external library.

**Comment by ssciolla** [comment]
Issues resolved:

- [x] Safari Mobile: Errors lingered when a user exited the Safari application from a page with open websockets, let the phone go to sleep, and then returned to the Safari application and page. Resolution: Errors now indicate that a reconnection is happening, and they disappear in a couple seconds.

**Comment by jlost** [comment]
[x] Safari Desktop & Mobile: If you visit a page that uses websockets (such as /edit/id), click an external link (such as in the MOTD), and then click back, these browsers will close the socket with a code of 1000 and also emit an error event with no error data. These errors will now disappear after a couple of seconds, when the socket reconnects.

**Comment by jlost** [comment]
- [ ] Firefox: Errors would briefly appear upon page refresh or just before navigating away from the website via the address bar. These are now suppressed.

- [ ] Chrome Mobile: If a user put their phone to sleep for a few minutes and then returned to the tab, the socket would be closed and have emitted an error event named TIMEOUT. These errors should now disappear in a few seconds, after the socket reconnects.

**Comment by teshsopher** [comment]
Tested and working in QA on 9/3
