### ISSUE TITLE
Just-in-time meeting creation

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#148]
Change to creating meetings at the moment the host is ready for the attendee because this is the only way that it will work with Zoom.

Zoom meeting design:
- Meeting is not created until host clicks a button to create it, it is no longer triggered by the attendee joining the line
- Attendee joins the line as Zoom type
- First, meeting must be assigned to a host before any Zoom meeting can be created
- Once the meeting is assigned to a host, ONLY THAT HOST sees the button: Create Meeting
- Once the host clicks Create Meeting, a meeting is created under the host's account
- Once the host clicks Create Meeting, the button changes to Start Meeting. This button launches the Zoom meeting start URL (the one that has a /s/ in it, not a /j/)
- Once the host clicks Create Meeting, other hosts see a button Join Meeting. This button launches the Zoom meeting join URL (the one that has a /j/ in it, not a /s/)
- After meeting created, the option to change the host is grayed out

Changes to In Person meeting design:
- Attendee joins the line as in person type
- First, meeting must be assigned to a host
- Once the meeting is assigned to a host, ONLY THAT HOST sees the button: Ready for Attendee
- Once the host clicks Ready for Attendee, the meeting moves to Meetings in Progress ( #230 )

**Comment by teshsopher** [comment]
I have a mockup for this: https://www.sketch.com/s/8621ed00-6017-4fd0-80e4-6af782047a38

I also did my best to address the issue of the Create Meeting button not being present until a host is assigned by adding a short text instruction.

**Comment by mfldavidson** [comment]
"Please Assign Host" works for me!

**Comment by jlost** [comment]
Closed by #129
