### ISSUE TITLE
input-group CSS class results in strange spacing, misalignment

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#154]
Minor issue, but it's been bothering me:

There is a CSS class for "input-group" that adds spacing around the entire field. Because spacing needs different depending on the context, sometimes this means there are strange cases of unaligned content/components, as seen below on the Manage Queues list:

<img width="654" alt="Screen Shot 2020-09-08 at 2 29 56 PM" src="https://user-images.githubusercontent.com/35741256/92514605-2c836b80-f1e0-11ea-80d8-058cb06d5d55.png">

I think we need one class (maybe not named exactly "input-group") that just adds top margins that can be used when an input form is part of a general page flow.

Maybe it doesn't have to be `input-group` specific...

**Comment by mfldavidson** [comment]
Fields such as add queue on manage page, add host on queue manage page, and add attendee on queue manage page are aligned now
