### ISSUE TITLE
Disambiguation of the "Edit" buttons

### ISSUE THREAD

**Issue by teshsopher** [tl-its-umich-edu/remote-office-hours-queue#156]
The edit buttons on a queue's page need some disambiguation.

- When edit is selected, the opened fields should have a label (Edit Description does, but Edit Title doesn’t)
- When edit is clicked, move focus to text field so screen reader reads the name (NVDA doesn’t go into focus mode, so it’s not reading the field name; It works on the title edit, but not the description edit)

A11y Team Recommendation: Have the field exist, but hidden when the page is loaded. This may make it easier for screen readers to adjust for the field changes.

Note: This change may be unnecessary for when the Queue Settings page(s) are up.

**Comment by jlost** [comment]
Looks like the edit buttons are no longer used after the Queue Settings page changes. Feel free to have a look in QA and reopen if I'm misunderstanding.

**Comment by ssciolla** [comment]
@jlost, the Edit button is still used for the Agenda field in `queue.tsx`. That's the only remaining use I'm aware of.

**Comment by teshsopher** [comment]
Since QA isn't really needed for this issue (I don't think anything was changed?), I'm moving this to done!

**Comment by ssciolla** [comment]
@teshsopher , could you please test that the input field for the Agenda Edit button field receives focus at the right times (i.e. not on initial page load if if it starts in an editing state, but always focused when it appears after clicking the Edit button)?

**Comment by ssciolla** [comment]
Also, probably worth checking that the Agenda field has the label you requested.

**Comment by teshsopher** [comment]
Tested and working in QA. The field also has the label!
