### ISSUE TITLE
"It's your turn" shows on closed queue

### ISSUE THREAD

**Issue by ksofa2** [tl-its-umich-edu/remote-office-hours-queue#164]
The "It's your turn!" message shows even on a closed queue

![IMG_9E3E682F0AB4-1](https://user-images.githubusercontent.com/152920/93782429-8f213200-fbf8-11ea-89fa-6f39333cbc48.jpeg)

**Comment by mfldavidson** [comment]
It should show, because you are still in line

**Comment by mfldavidson** [comment]
I am going to close this as a won't do @ksofa2 since this is the intended behavior but feel free to argue
