### ISSUE TITLE
Websockets don't auto-reconnect on Chrome, or do but error doesn't clear

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#168]
This is hard to reproduce, but on Chrome Desktop, if a page is idle for a long time causing the user connection to drop (and probably queue connection too but I did this on a page that doesn't have a queue connection), it is unclear whether it auto-reconnects or not. The error shows up and stays there, but it appears to still work...
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31591389/93819548-de338b00-fc29-11ea-9245-94a1c6aeba82.gif)

On Chrome Mobile (also hard to reproduce) if a page is idle for a long time, both user and queue connection drop and the error just sits there. If I try to, say, add an agenda as an attendee on a queue where I am in line if it is showing these errors, it doesn't save, so it does seem that they aren't auto-reconnecting.

**Comment by jlost** [comment]
I've noticed this before as well - by accident. I spent some time yesterday trying to repro this but wasn't able to. Would it be acceptable to "fix" (really, mitigate the confusion of) this by telling the user to refresh after *x* number of retries have elapsed?
