### ISSUE TITLE
Docker ModuleNotFoundError: No module named 'uvloop'

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#176]
Error now occurs on Docker build:
```
ModuleNotFoundError: No module named 'uvloop'
```

Fix: use `uvicorn[standard]`

https://github.com/tiangolo/fastapi/issues/2181

**Comment by mfldavidson** [comment]
@ssciolla can you test this please and move to Done if working?

**Comment by ssciolla** [comment]
Sure, @mfldavidson. @jlost, I'm curious, why aren't the packages `gunicorn 'uvicorn[standard]' psycopg2-binary` in `requirements.txt`? Unless I'm missing something, seems like we would would have avoided this problem if we had pinned to a compatible version (`~=`) like we with the other dependencies.

**Comment by jlost** [comment]
The idea is to decouple hosting dependencies from application dependencies. You could swap gunicorn for some other server and it would have no bearing on the app. But we can still version lock them in this file, and it would be a good idea.

**Comment by ssciolla** [comment]
Gotcha, separating them makes sense for that reason. Version locking them in `Dockerfile` or a separate `host_requirements.txt` makes sense to me.

**Comment by jlost** [comment]
#186

**Comment by ssciolla** [comment]
Docker build is now working well, and linked issue (#186) addressed any lingering concerns. Moving to Done.
