### ISSUE TITLE
Allow owners to open and close queues

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#18]
Allow instructors to "open" a queue for queuing or "close" a queue to restrict further queuing. (Like opening a store and closing a store)

Noted as high priority by 3 beta testers

**Comment by psteffes** [comment]
@jlost @mfldavidson @ksofa2 Do we just want something like an `is_open` BooleanField on the queue? Alternatively, if we think the use may expand we could just create a `status` and start with open/closed choices.

**Comment by mfldavidson** [comment]
That's a good question. I could see us someday needing different statuses and it might be smart to build that in now with a status model. That's not really any more technically difficult or risky, right? I can't think of why it would be.

**Comment by mfldavidson** [comment]
@teshsopher do you have a design for this functionality?

**Comment by teshsopher** [comment]
I have some preliminary designs that I've just uploaded to the mockups (https://sketch.cloud/s/0W0gb). The first option has a "Settings" page for the queue, which will be better if we add more individual queue settings, like privacy, etc. Option 2 has the "Open/Close" status on the Manage page, which is good if there will only be one or two additional individual queue settings added to the page.

**Comment by psteffes** [comment]
Nope, I'll go with status then!

**Comment by jlost** [comment]
As I developed this, I absentmindedly threw together a UI implementation as I had forgotten about @teshsopher's mockups...Sorry about that! My implementation can be seen on dev. The differences are as follows:
1. I included the status field directly on the queue edit page instead of nesting it in a "settings" subpage, because right now it's the only such field. 
2. I used a toggle instead of a dropdown because there are only two states, open/close (corresponding to "on/off"), and thought it made some visual/intuitive sense. But I'm not married to this approach and could even more easily implement a select.
3. I put a gray alert at the top of the "queue" page if the queue is closed, and removed the "Join" button. Naturally, I'm fine with putting it at the bottom and changing the text. But there is one state I see you haven't addressed yet, and that's when you're waiting in a queue and the hosts close it while you're waiting. This seemed like a realistic possibility to me, because the hosts might want to prevent anyone new from joining while they finish up their current line. I used the following text for that state:
>This queue has been closed by the host. You're still in line, but if you leave the line you will not be able to rejoin until the queue is reopened.
I'm thinking that if a user is waiting to be served and they see red pop up near the "Leave" button because the queue has closed, they might panic... What you do you think?

**Comment by teshsopher** [comment]
1. I agree that, since this is really the only setting that would be in a submenu, it is good to put it directly on the Manage page.
2. I like the toggle, but I need to make sure that it's accessible for screen readers
3. I do think that the alert at the top is fine, since that's where the users are supposed to be looking to see their queue status. However, would it be good remove the alert where the "Your turn is coming up" alert is when the queue is closed? That way there is only one alert competing for their attention.

**Comment by jlost** [comment]
I could see multiple alerts being noisy. Between silencing the "queue closed" alert and silencing the "your turn is coming up," I think it would be better to silence the former. It's very important that the user join the meeting, but a user leaving the queue while expecting to rejoin later is a relative corner case. I could also just remove the "queue closed" alert entirely if that would simplify things. I wouldn't want it to add confusion.

**Comment by mfldavidson** [comment]
Re: competing alerts, I agree with James that priority goes to encouraging the user to get in the meeting rather than notifying them that if they leave, they can't rejoin. What if, instead of an alert at all, they are just informed that they can't rejoin only if they click to leave the line?

**Comment by mfldavidson** [comment]
In the pop-up I mean

**Comment by teshsopher** [comment]
I think where I'm getting a little lost is what the ideal flow for the user is here. If it's that they should still join the meeting, despite the queue being closed, then I think having the two alerts is fine, but the language in the closed queue alert should read something like, "The queue is closed, but you are still in line. Please communicate with the host to ensure the meeting will still happen."

**Comment by teshsopher** [comment]
Though, I do like the idea of having some language in the pop up for being unable to rejoin the line in the pop up if the person clicks to leave the line. I can mock this up and do some user testing to see what language/set up looks better.

**Comment by mfldavidson** [comment]
What if, when a host closes the queue that still has people in it, we make them select whether to delete all the meetings in the queue, or send a notice to the user that the queue is closed but their meeting will still happen?

**Comment by teshsopher** [comment]
I like that idea! 
The alert for users would have to be based on what the host chose to do. So the alert for users when they are removed from queue should read, "The host has closed the queue, and you have been removed from the line. You may rejoin the queue when the host re-opens it." And the alert for when users are still in line should be similar to what I had said before, but more like, "The queue is closed, but you are still in line. The host will meet with you when they are available."

**Comment by jlost** [comment]
I like that from a UX perspective, but from a technical POV it would add a lot of complexity. The front-end would need to know that the user recently left a given queue, and how/why (queue closed). This kind of reactivity might be easier if we changed from an API polling architecture to a realtime websockets one (a state change message is "pushed" to the client along with a reason). My inclination is to avoid "sending one-off messages" to users via the app, and to ask hosts to do that manually via Hangouts instead. If we truly have enough compelling reasons to want to do something like that, let's make it a separate issue.

FWIW, my preferred solution so far would be to notify the user via a confirmation dialog that the queue has closed if they try to leave the line.

**Comment by teshsopher** [comment]
Yeah, if that poses too much technical complexity, then I think sticking with the original alert, but using the changed language ("The queue has been closed, but you're still in line. Please contact..." etc) with the pop up is still a good option.

**Comment by jlost** [comment]
Queue is closed:
![image](https://user-images.githubusercontent.com/11338926/80991570-39ddb300-8e06-11ea-8593-b098cb77ac87.png)

When you click "Leave the line":
![image](https://user-images.githubusercontent.com/11338926/80991489-229ec580-8e06-11ea-8b17-71793b8e39e6.png)

No longer in queue:
![image](https://user-images.githubusercontent.com/11338926/80991884-b375a100-8e06-11ea-90e6-89e8388b80b8.png)

**Comment by jlost** [comment]
#37

**Comment by mfldavidson** [comment]
I just tested this and did not get the pop-up when I left the line, I was just removed with no popup at all @jlost

**Comment by jlost** [comment]
I didn't deploy these to dev, but I can. Just a sec.

**Comment by jlost** [comment]
By the way, do we want hosts to be able to add attendees even if the queue is closed?

**Comment by mfldavidson** [comment]
Hmmm that's a great question. How hard would it be to allow hosts to add but not allow attendees to join? I like that idea...

**Comment by jlost** [comment]
Pretty easy, I just did it and then deployed.

**Comment by jlost** [comment]
Looks like the confirmation broke though... stand by.

**Comment by jlost** [comment]
Fixed it - I made a mistake while merging in the work from dev.

**Comment by teshsopher** [comment]
So, I haven't gotten the official accessibility review; however, I took a look at this feature myself, and it's not entirely accessible for screen readers the way it's set up now. Right now, these users are hearing "Status, checked, checkbox" which isn't telling them 1. what this is for, and 2. what checked means. An easy way to make this accessible is to change the label. I suggest changing "Status" to "Open Queue," but I am open to other wordings!

**Comment by jlost** [comment]
@teshsopher @mfldavidson I changed it to a plain select instead of a toggle, because I was also seeing weird screen reader behavior I couldn't easily resolve. NVDA seems to be reading it coherently. It now matches your original mockup.

**Comment by mfldavidson** [comment]
That makes sense to me
