### ISSUE TITLE
Prompt host to enable SMS notifications

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#182]
We want to make sure that hosts know about the option to enable SMS notifications at the appropriate time.

Where it currently says "No meetings in queue" in a gray box, change it to the following:

> No meetings in queue. Get notified by SMS (text) message when someone joins your empty queue by adding your cell phone number and enabling host notifications in your [User Preferences](/preferences/).

Questions: is this the best UX? I do not want us to have to go out and check if someone has this set, that's too technically complex for right now, so does this wording confuse people and make them think that we're saying they don't have it set even if they do? Would this be better?

> No meetings in queue. If you have opted in to host notifications in your [User Preferences](/preferences/), you will get an SMS (text) message when someone joins your empty queue.

@teshsopher and Joel (will send to Joel separately as he isn't on GitHub) I'd appreciate your input on the wording here.

**Comment by jlost** [comment]
How does this look: 
![image](https://user-images.githubusercontent.com/11338926/97048364-4c7cad80-1548-11eb-8a38-b170f0e025d2.png)

**Comment by teshsopher** [comment]
For the wording, I think that we could say, "No meetings in queue. Make sure you've opted into host notifications in User Preferences to receive an SMS (text) when someone joins your empty queue."

As far as the look, the link doesn't have enough color contrast with the background. I think that, with this addition, we may want to consider if we need to put the message in one of these gray boxes. Maybe we could do something like this:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/63423382/97180470-7b756800-1770-11eb-96d6-cfcd57206908.png">

**Comment by mfldavidson** [comment]
I think @teshsopher 's recommendation about removing the gray box is good. Let's do that.

Joel recommended this wording and I think I'd like to go with it because I think it is the gentlest/doesn't make it seem required to opt in:
> Did you know? You can get notified by SMS (text) message when someone joins your empty queue by adding your cell phone number and enabling host notifications in your [User Preferences(/preferences/).

@jlost

**Comment by teshsopher** [comment]
Tested and working in QA
