### ISSUE TITLE
Prompt attendee to enable SMS notifications

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#184]
We want to make sure that attendees know about the option to enable SMS notifications at the appropriate time.

Just below "Your number in line", IF the number is GREATER THAN 1, show this blurb:

> Get notified by SMS (text) message when it's your turn by adding your cell phone number and enabling attendee notifications in your [User Preferences](/preferences/).

Questions: is this the best UX? I do not want us to have to go out and check if someone has this set, that's too technically complex for right now, so does this wording confuse people and make them think that we're saying they don't have it set even if they do? Would this be better?

> If you have opted in to attendee notifications in your [User Preferences](/preferences/), you will get an SMS (text) message when it is your turn.

@teshsopher and Joel (will send to Joel separately as he isn't on GitHub) I'd appreciate your input on the wording here.

**Comment by jlost** [comment]
How's this visually: 
![image](https://user-images.githubusercontent.com/11338926/97048118-e8f28000-1547-11eb-820d-8d8d4e7ff6e5.png)

**Comment by teshsopher** [comment]
For wording, we could say, "Make sure to opt into attendee notifications in User Preferences to receive and SMS (text) when it's your turn."

For the layout, the link doesn't have enough contrast, but this is one of the better ways to make sure attendees see it. Another option could be to put it above the info box like:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/63423382/97181262-74028e80-1771-11eb-9b03-e123333763af.png">

The problem with the second option is that attendees might skip over the text.

**Comment by mfldavidson** [comment]
I agree with the concern that attendees will skip over it. I'd like to stick with the layout James has recommended if we can. Is it bad practice to change the color of just this one link hard-coded?

Similarly to the other one, I'd like to apply Joel's recommended verbage here:

> Did you know? You can receive a SMS (text) message when it's your turn by by adding your cell phone number and enabling attendee notifications in your [User Preferences](/preferences/).

**Comment by jlost** [comment]
I believe Sam's fix here will solve the problem of link color contrast in light blue alerts:
https://github.com/tl-its-umich-edu/remote-office-hours-queue/pull/191/files#r512158694

**Comment by jlost** [comment]
Here's how that looks: 
![image](https://user-images.githubusercontent.com/11338926/97454508-376b9a00-190d-11eb-9d94-b32962a97b5e.png)

**Comment by jlost** [comment]
I applied the wording changes and will rely on Sam's accessibility tweaks for the contrast problem (#191 , #155)

**Comment by teshsopher** [comment]
Tested and working in QA
