### ISSUE TITLE
Lock pip requirements for hosting

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#186]
As @ssciolla mentioned in #176, updates to packages in `Dockerfile` can break the build, so they should be locked to a compatible version either there or in a separate `host_requirements.txt`.

**Comment by ssciolla** [comment]
Ideally this would be QAed by someone who didn't review the pull request, but I've been working off `master` and I reviewed the linked issue leading to this change. I think we're good to go, I'm moving to Done.
