### ISSUE TITLE
How would a meeting end up with no attendees?

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#197]
While testing on `dev`, I managed to discover a bug (that I don't know how to reproduce) whereby a meeting can end up with no attendees, which throws a JS exception because the UI (in `queueManager.tsx`) assumes meetings have at least one attendee. During the testing, I was deleting meetings, and I was changing a test user's first and last name and email address (actually repeating my own, which caused a separate login problem, but which won't occur in production since email addresses aren't managed manually). This will require more investigation to figure out exactly what happened.

The problematic queue can be found at [https://dev.officehours.it.umich.edu/manage/41/](https://dev.officehours.it.umich.edu/manage/41/)

**Comment by jlost** [comment]
One way it could happen:
* Create meeting for an attendee
* Delete that attendee
* Deletion cascades through the meeting, creating a meeting with no attendees

**Comment by ssciolla** [comment]
This is some internal information on this bug (explicit access is required): https://docs.google.com/document/d/14octPEnQ8MMMmwgu4OgDszPVHv4isom4vSciHNn4hng/edit?usp=sharing

**Comment by ssciolla** [comment]
We also just had an incident today where three meetings with attendees ended up in the queue, but they didn't cause a JavaScript error. It looked like this:
![Screenshot 2023-06-30 115459](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/35741256/39cbf1d9-a0b1-4acf-a4b0-c77745db29a6)

I couldn't determine from logs that caused this. There were no tracebacks about this, and no evidence of those meetings being created in response to API calls. Puzzling...

**Comment by jonespm** [comment]
We had what I believe is issue again today. This caused the manage page for a specific queue not to work.

When it got to this line in the StartedMeetingEditor there it returned undefined. I had to manually clear the meetings with the UI. 

https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/12e2185faf35307564bea910ff1baad7bef1ff76/src/assets/src/components/meetingTables.tsx#L141

The browser error was
`TypeError: Cannot read properties of undefined (reading 'first_name')
`

And within the javascript object it has 

`attendees: []`

**Comment by jaydonkrooss** [comment]
@HemanginiShah  @jxiao21  I've created an invalid meeting to view in ROHQ QA by tweaking the database, just to verify that this is how we'd like to handle this issue: https://qa.officehours.it.umich.edu/manage/483/

Looks like the page finally handles this scenario, with the delete buttons available for the queue managers to remove the invalid meeting with a missing attendee. If you do try deleting one of the users, please let me know if you want to restore this page to what it looked like originally and I can do it again.
![Screenshot 2024-06-19 at 12 17 57 PM](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/147423601/9059a4f4-2bbf-4b3b-ace8-2ce9b881c424)

**Comment by hemashahumich** [comment]
Tested with Jaydon and looks good.
