### ISSUE TITLE
Keep focus on CopyField button

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#202]
In terms of the "Copied" announcement, keeping focus on the button is the best, since folks may not know that they would be moving from the button to the URL field.

_Originally posted by @teshsopher in https://github.com/tl-its-umich-edu/remote-office-hours-queue/issues/160#issuecomment-718731853_

**Comment by teshsopher** [comment]
@ssciolla I'm still seeing the issue where, when the copy button is clicked, focus goes to the URL field

**Comment by ssciolla** [comment]
@teshsopher, sorry, I hadn't started a new build yet in OpenShift, I will DM you when it's done.

**Comment by teshsopher** [comment]
Perfect, tested and working in QA!
