### ISSUE TITLE
Hover indicator for Home and Resources & Support

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#204]
When hovering over your uniqname in the upper right, the color changes to show that you're hovering over it. This does not occur for Home nor for Resources & Support. Should it?

Hovering over my uniqname:
![image](https://user-images.githubusercontent.com/31591389/97913353-26ab9180-1d1c-11eb-89db-8881b5919731.png)

Hovering over Home or Resources & Support:
![image](https://user-images.githubusercontent.com/31591389/97913374-2f9c6300-1d1c-11eb-8789-f793e8d6690b.png)

**Comment by vjcao** [comment]
Is it ok if I work on this issue?

**Comment by mfldavidson** [comment]
Yes please, thank you so much @vjcao

**Comment by mfldavidson** [comment]
Tested everywhere I can find where this would appear, which turns out to only be the header nav. The hover on Home and Resources & Support looks fantastic. I was similarly worried that the gray for the dropdown might not provide enough contrast against the black, but @teshsopher approved it so I will not worry. Great work on this issue @vjcao . You'll see your work reflected in production mid next week!
