### ISSUE TITLE
Ordering of queues on My Meeting Queues (/manage)

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#205]
Order meeting queues on /manage. Should it be:
- By ID
- By name
- By status and then either ID or name?

Up for discussion.

**Comment by ssciolla** [comment]
I got started on this. If we wanted to do something really basic, this might suffice: https://github.com/tl-its-umich-edu/remote-office-hours-queue/compare/master...ssciolla:issue-205-sort-queues?expand=1

I'm sorting by status and ID descending (that can be tweaked easily). My initial thought was that the `open` and most recently created queues should go first. See screenshot below.
<img width="500" alt="Screen Shot 2020-11-12 at 4 46 22 PM" src="https://user-images.githubusercontent.com/35741256/99000624-946b7080-2507-11eb-927e-9a115735ff1d.png">

If we expected these tables to get really large, to the point where pagination and user-activated sorting by column would be desirable, we might want to look at something like this: https://react-bootstrap-table.github.io/react-bootstrap-table2/

Let me know if you have any thoughts, @mfldavidson, @jlost, @teshsopher

**Comment by ssciolla** [comment]
We're going to wait on a more sophisticated table ordering approach (using a custom component), so we just need to decide on a sorting algorithm.
