### ISSUE TITLE
Align Manage Queues language

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#219]
On homepage, link is "Manage Your Own Queues", but in dropdown, it is "Manage Queues." Change link on homepage to "Manage Queues" to align language and make it clear they are the same page.

**Comment by HemanginiShah** [comment]
5/31/2023 - QA test completed successfully.  Now both places the same text is visible. On homepage, link is "Manage Queues", and also in dropdown, it is "Manage Queues."
