### ISSUE TITLE
Change host disclaimer

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#228]
At the top of the meeting list, a blue info disclaimer shows "Once you create a Zoom meeting, you cannot change it to another host" but only if Zoom is an allowed meeting type on that queue

**Comment by ssciolla** [comment]
@mfldavidson, so based on the discussion on issue #230, I'm going to change the text here to something like this and always show it?

"Once you start a video-conferencing meeting or indicate you are ready for an attendee in person, you cannot re-assign the meeting to another host."

**Comment by mfldavidson** [comment]
Sounds good to me!

Maggie Davidson, she, her, hers <https://www.mypronouns.org/> pronouns

Service Manager | Zoom, Student Explorer, Remote Office Hours Queue

Information and Technology Services | University of Michigan

jmaggie@umich.edu | LinkedIn: mfldavidson
<https://www.linkedin.com/in/mfldavidson/>
