### ISSUE TITLE
Notification on queue join in Edit page

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#23]
"I wish that there was a notification sound (that I could turn off if I wanted to) when another person joined the queue."

Noted as high priority by 2 advisor beta testers

**Comment by mfldavidson** [comment]
Requested by a lot of people so far, here are a few:
- [TDX 153155](https://teamdynamix.umich.edu/TDNext/Apps/31/Tickets/TicketDet.aspx?TicketID=153155)

**Comment by mfldavidson** [comment]
Only if number in queue goes from 0 to 1
