### ISSUE TITLE
Once meetings are started, move into Meetings in Progress

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#230]
Once Start Meeting has been clicked on a Zoom meeting, or Ready for Attendee clicked on In Person meeting, that meeting moves up in the page to a separate section above Meetings in Queue called "Meetings in Progress". This table contains the following columns: Attendee, Host, Meeting Actions. No queue # 

Host is grayed out if the meeting type is Zoom, changeable if the meeting type is In Person

The Meeting Actions are:
- Zoom Meeting only: Start Meeting (for the assigned host) or Join Meeting (for all other hosts)
- Join Info
- End Meeting (instead of trash, this is what removes it)

**Comment by teshsopher** [comment]
I have a mockup that includes this (if references are needed): https://www.sketch.com/s/8621ed00-6017-4fd0-80e4-6af782047a38

**Comment by ssciolla** [comment]
Thanks, @teshsopher, I have something working I believe, but I think I may wait until the Zoom piece is merged before submitting PR.

**Comment by ssciolla** [comment]
@mfldavidson, I have a question. It looks like @jlost implemented logic in the backend that makes it so all meetings -- regardless of type  -- cannot have their hosts reassigned once they have been started (i.e. the user pushes "Start Meeting" or "Ready for Attendee"). This is contrary to what you have requested above, but I thought it might be wise to pause and consider this point more. It would help to keep the codebase simpler if we used the same logic in the frontend, and it could reduce confusion. I'm thinking of the situation where a host removes an assignment entirely once the the meeting is "In Progress", leaving the user without someone to meet with. Do you have any thoughts about this?

**Comment by mfldavidson** [comment]
I am ok with it not being changeable once in progress, regardless of meeting type.

**Comment by ssciolla** [comment]
Thanks, @mfldavidson. I'll proceed with that approach. As an alternative, we could have a "Add back to queue" button, that moves it from "In Progress". I think I remember someone (not me) suggesting this in the past. In practice, that might mean just deleting an existing meeting and re-creating it with the same attendee. If that's something you think would be valuable, perhaps it's worth an issue?

**Comment by mfldavidson** [comment]
We ended up not doing that at least for now because of the complication of
what if the attendee has already joined the meeting

Maggie Davidson, she, her, hers <https://www.mypronouns.org/> pronouns

Service Manager | Zoom, Student Explorer, Remote Office Hours Queue

Information and Technology Services | University of Michigan

jmaggie@umich.edu | LinkedIn: mfldavidson
<https://www.linkedin.com/in/mfldavidson/>
