### ISSUE TITLE
Attendee view info about place in line

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#231]
# When attendee is 2+ in line (no longer just show this if <=5th--show all the time)
Yellow alert
### Zoom or BlueJeans:
> It's not your turn yet, but the host may be ready for you at any time. Pay attention to this page so you can join the meeting once it is created.

### In-Person:
> It's not your turn yet, but the host may be ready for you at any time. Pay attention to this page--we will tell you when the host is ready. Make sure you are nearby the in-person meeting location.

# When attendee is first in line and Create Meeting/Ready for Attendee has NOT been clicked (i.e. not in progress):
Green alert
### Zoom or BlueJeans:
> You're up next, but the host isn't quite ready for you. Pay attention to this page so you can join the meeting once it is created.

### In-Person:
> You're up next, but the host isn't quite ready for you. Pay attention to this page--we will tell you when the host is ready. Make sure you are nearby the in-person meeting location.

# When Create Meeting/Ready for Attendee HAS been clicked (Meeting moves to Meetings in Progress):
Green alert
### Zoom or BlueJeans:
> The host is ready for you! If you haven't already joined the meeting, follow the directions to join it now.

### In-Person:
> The host is ready for you! If you haven't already, go to the in-person meeting location to meet with the host.

**Comment by ssciolla** [comment]
Because there is no way currently to know whether the host has joined the meeting, this workflow will likely need to be modified a bit. I will talk with @mfldavidson later today.

**Comment by mfldavidson** [comment]
Tested and working in QA except for "when attendee is first in line" part has a bug--new issue #269 for the bug, so moving this to done.
