### ISSUE TITLE
JIT VC meetings - attendee information

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#233]
Before the meeting is created, the Join Meeting button should be grayed out.

Before the meeting is created, show this message just above "Join Meeting" button (where it currently says "The host will join...")
> The host has not created the meeting yet. You will be able to join the meeting once it is created. We'll show a message in this window when it is created -- pay attention to the window so you don't miss it!

Once the meeting is created, show this message just above "Join Meeting" button (where it currently says "The host will join...")
> The host has created the meeting. Join it now! The host will join when they are ready for you.

![Joining the Meeting and Having Trouble with Video info boxes](https://user-images.githubusercontent.com/31591389/99694175-202a5300-2a5a-11eb-8f7a-cf81e023f91d.png)

Joining the Meeting box should be:
> #### Joining the Meeting
> Once the meeting is created, click Join Meeting to join the meeting and wait for the host. Download the app and test your audio now. Refer to [link] for additional help getting started.
The link and text for BlueJeans should be: [Getting Started with BlueJeans at U-M](https://its.umich.edu/communication/videoconferencing/blue-jeans/getting-started)
The link and text for Zoom should be: [Getting Started with Zoom at U-M](https://its.umich.edu/communication/videoconferencing/zoom/getting-started)

Having Trouble with Video? box should remain the same for BlueJeans.
The same box for Zoom should be (differences are the phone #, the link to international numbers, and terminology of meeting host and host key in last sentence):
> #### Having Trouble with Video?
> Having problems with video? As a back-up, you can call 1.312.626.6799 from the USA (or [find your international number to call in from outside the USA](https://umich.zoom.us/profile/setting?tab=telephony) - click See All Numbers under Toll Call to see all countries) from any phone and enter [id]#. You do not need a host key or participant ID.

Also add same having trouble with video blurb to host join info if meeting type is Zoom

**Comment by ssciolla** [comment]
@mfldavidson, do we know the international number link for Zoom yet?

**Comment by mfldavidson** [comment]
I apologize for not coming back to this @ssciolla thank you for the reminder. Unfortunately there is no one link we can use that shows all numbers for OUR account unless someone is logged in. So I think it will have to be as follows, which is ugly:

> #### Having Trouble with Video?
> Having problems with video? As a back-up, you can call 1.312.626.6799 from the USA* from any phone and enter [id]#. You are not a meeting host, so you do not need a host key.
> *Calling in from outside the USA? [Find your international number](https://umich.zoom.us/zoomconference). To see all numbers for the U-M account, make sure you are logged in to Zoom by clicking Sign In in the upper right of the Zoom International Dial-In Numbers page if you aren't already signed in.

**Comment by mfldavidson** [comment]
@ssciolla I updated the original issue at the bottom with the final Zoom international call-in link and info

**Comment by ssciolla** [comment]
> Before the meeting is created, the Join Meeting button should be grayed out.

@teshsopher, thinking back to our validation discussions, I think we've moved away from using `disabled` button styling to indicate something isn't yet ready to be used. Do you have any thoughts about communicating this detail in another way, so that users know that a "Join Meeting" button is coming but can't actually use it until it's ready?

**Comment by ssciolla** [comment]
@teshsopher, I'm thinking about something like this, which isn't that different from what we currently have, but does call attention to the fact that a button will appear.

<img width="716" alt="Screen Shot 2020-12-07 at 4 47 11 PM" src="https://user-images.githubusercontent.com/35741256/101409516-012a1e80-38ac-11eb-9485-4c09f5a26524.png">

**Comment by teshsopher** [comment]
I think this is good! The language works and, since it's bold, it will hopefully stand out more so folks won't miss it!

**Comment by ssciolla** [comment]
Based on the requested text, I am assuming that the "Joining the Meeting" and "Having Trouble with Video? cards should be visible even before the meeting has been created. Because the meeting number won't exist until the meeting is created, I've added some placeholder text in that case. Here's what it will look like for Zoom (pre-meeting creation). @mfldavidson and @teshsopher, I'm happy to tweak the language as desired.

<img width="700" alt="Screen Shot 2020-12-08 at 12 31 00 PM" src="https://user-images.githubusercontent.com/35741256/101519565-4e140080-3951-11eb-9fab-02d22ee38304.png">

**Comment by ssciolla** [comment]
Hm, thinking about the pre-meeting creation Cards a little more. The one-touch dial-in link will be broken as well if there is no meeting number. Maybe we should hide the "Having Trouble with Video?" box until the meeting is created?

**Comment by teshsopher** [comment]
Would it be worth having a sort of "post-join" meeting page? For instance, when the attendee clicks the Join Meeting button, they are taken to a webpage where they can see the meeting details (host, agenda, etc) and could re-join the meeting if they lost connection or had to drop out of the meeting. Then, on that page, we can have the help cards for folks who are having issues after they've tried to join the meeting the first time

Kind of like Zoom does, if that makes sense

**Comment by ssciolla** [comment]
> Would it be worth having a sort of "post-join" meeting page?

Interesting thought, though with SPAs, it doesn't actually have to be a new page -- at which point, maybe we're pretty close to that already? A new page or UI would require more back-and-forth than I think we have time for. For now, I'm going to just now show the "Having Trouble with Video?" or dial-in info in the "Join Info" pop-up until the meeting is created. If you think there should be alternative text in this case, let me know, I can add that or modify accordingly.

**Comment by teshsopher** [comment]
> Interesting thought, though with SPAs, it doesn't actually have to be a new page

I didn't know that, that's pretty interesting! It's definitely something to think about, but I think your solution of hiding the joining instructions until the meeting is available is good!
