### ISSUE TITLE
Field for in-person meeting location on queue if queue has in-person meeting type option

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#234]
If In-Person is selected as a meeting type option, an additional field should become available just below Meeting Types in Add Queue and Settings.

> #### In-Person Meeting Location
> Attendees who select to meet in-person will be instructed to meet at this location. Enter all information an attendee would need to know, such as a street address, building name, and/or room number.

The field should be a text field with a character limit of 100 and the same validation used in the queue name field.

In the attendee view, BEFORE joining the line, the location should show as an additional bullet below "You are not in the meeting queue yet" but only if In Person is an allowed meeting type:
> - In-person meetings will take place at: [location]

AFTER joining the line, if the meeting type is In Person, the location should show below "Meeting Via" above "Agenda":
> Meet at: [location]

**Comment by vjcao** [comment]
May I work on this issue as well? Thank you.

**Comment by mfldavidson** [comment]
Please do! Thank you @vjcao

**Comment by vikaschanduri** [comment]
Hi, would be great to work on this issue as well!

**Comment by ssciolla** [comment]
> Hi, would be great to work on this issue as well!

@vikaschanduri, I think we're good on this issue now, @vjcao has it pretty much done.

**Comment by mfldavidson** [comment]
![image](https://user-images.githubusercontent.com/31591389/117322345-ed371880-ae5b-11eb-9bf7-6983c7c407fc.png)

Tested and passed:
- [x] Adding this feature to a queue that already allowed in-person meetings didn't break anything since it isn't required
- [x] Checking in-person as a meeting type in queue settings shows the field, unchecking it hides it
- [ ] Checking in-person as a meeting type in add queue shows the field, unchecking hides it
- [ ] Prior to joining the queue, attendees see "The host(s) have not specified an in-person meeting location." if the field is blank AND in-person is enabled
- [ ] Prior to joining the queue, attendees do NOT see "The host(s) have not specified an in-person meeting location." if in-person is not enabled
- [ ] Prior to joining the queue, attendees see the in-person meeting location if the field has any characters other than a space in it
- [ ] Prior to joining the queue, attendees see "The host(s) have not specified an in-person meeting location." if the field only has blank spaces in it AND in-person is enabled
- [ ] After joining the queue for a Zoom meeting, in-person meeting location does not show at all
- [ ] After joining the queue for an in-person meeting, attendees see "Meet At: The host(s) have not specified an in-person meeting location." below "Meeting Via:" if the field is blank
- [ ] After joining the queue for an in-person meeting, attendees see "Meet At: The host(s) have not specified an in-person meeting location." below "Meeting Via:" if the field only contains blank spaces
- [ ] After joining the queue for an in-person meeting, attendees see "Meet At: [in person meeting location]" below "Meeting Via:" if the field contains characters other than a space in it
- [ ] If the attendee changes the meeting type to Zoom, "Meet At" disappears

**Comment by mfldavidson** [comment]
Testing passed, excellent work @vjcao . You'll see this in prod starting mid next week!
