### ISSUE TITLE
Track & Show Meeting Assignees

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#24]
Separate out meetings that are in session with a host from meetings that are not yet in session with a host. Show which host "claimed" the meeting. Probably use who clicked Join Meeting? And make sure they know that once they click it it is "theirs"

Noted as high priority by 4 advisor beta testers

**Comment by mfldavidson** [comment]
Thought discussed in standup yesterday: probably don't want to use Join Meeting, esp since this means if they call in it's not recorded. Maybe add a separate button for "Assign to Me" or something? Lots of UX stuff to think through here on both the host and attendee side. This is a hefty issue.

**Comment by mfldavidson** [comment]
@teshsopher

**Comment by teshsopher** [comment]
I've (hopefully) mocked up this design here: https://www.sketch.com/s/d3e8e90e-86a6-4d57-ba0e-33e40954eda9

Let me know if I'm misunderstanding this issue

**Comment by jlost** [comment]
I like it. I think a Select2-ish control would work for "Assign to Host":
![image](https://user-images.githubusercontent.com/11338926/80622598-028e9100-8a17-11ea-9ef6-0c49ae774845.png)

**Comment by jlost** [comment]
If the most common use case is to assign to yourself, I could move always move the current user to the top of the select.

**Comment by teshsopher** [comment]
Yeah, I anticipate that assigning to yourself would be the most common use case, so having the current user at the top would be good.

**Comment by jlost** [comment]
@teshsopher In dev & ready to be reviewed.

**Comment by teshsopher** [comment]
It looks good and works for me!
