### ISSUE TITLE
Upgrade node 12 LTS to currently supported LTS

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#253]
We updated MyLA from Node 12 to 14. [The even node versions](https://nodejs.org/en/about/releases/) are the LTS maintenance and 12 just entered it's LTS stage. 

Also if you switched the image from node:12-alpine to node:14-slim  when upgrading it would ensure that it builds without the rate limit issue on Openshift.

The Dockerfile changes for MyLA were minimal but there were a few other packages that were updated. https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1115

https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/266e38de7b3684b2b1d20ba184d0b0150ecfa85a/src/Dockerfile#L2

**Comment by jonespm** [comment]
It looks like even 16 LTS ends support in a few months. https://endoflife.date/nodejs

Going to 18 LTS would seem to be the best to target but don't know the effort for that.

**Comment by zqian** [comment]
verified the node upgrade is in place along with other library updates. No issues reported with the browser console output.
