### ISSUE TITLE
userWebSocketError in queueManager is not registered for ErrorDisplay

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#256]
This is a somewhat minor issue, but my IDE is telling me `userWebSocketError` is unused in `queueManager.tsx`. We should register a `User Connection` error source to be used with `ErrorDisplay`, so we're aware if that particular WebSocket connection has issues.

**Comment by mfldavidson** [comment]
This seems like one that is sort of tested by default when merged so moving to done

**Comment by ssciolla** [comment]
Yeah, it's minor. You could probably test it by going to the `QueueManagerPage` and turning off your WiFi/Ethernet connection.
