### ISSUE TITLE
Zoom meetings should be created with Join Before Host off

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#266]
When a Zoom meeting is created, join before host should be OFF

This is `join_before_host` in settings https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate -- we want to change this from `true` to `false`

This issue is dependent on #265 -- we SHOULD NOT implement this change if 265 is not done

**Comment by jlost** [comment]
Fixed by #279
