### ISSUE TITLE
Change "End Meeting" button under "Meetings in Progress" to use trash icon

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#272]
The button that says "End Meeting" once a meeting is in progress should be changed to the remove meeting trash icon.

**Comment by ssciolla** [comment]
@mfldavidson, I agree that the button and dialog should use consistent language.

I'm thinking about this a little more, and I'm slightly thrown off by the "End Meeting" language we're preferring. I will defer to you, but I wanted to share my thinking. Does "End Meeting" imply to users (erroneously) that a call will be sent to Zoom (or whatever service) that actually ends/terminates the meeting there? Or are they going to know a ROHQ meeting and a Zoom meeting are separate entities, with separate lifecycles? Sticking with "Remove Meeting", a trash icon, or "Mark as Done/Finished" might more clearly communicate the technical reality. That was my reaction, but maybe I'm alone here. @jlost or @teshsopher, I'd be curious to hear your opinions, as well.

**Comment by jlost** [comment]
I prefer for the interface to reflect the technical reality, since I think it improves peoples understanding of their app and their ability to use it, decreasing number of tickets and making it easier for us to explain to users how and why things work the way they do. So I'm in agreement with @ssciolla here, although it's not a super strong preference.

**Comment by teshsopher** [comment]
I'm leaning more toward using "Remove Meeting"/the trash icon for this too.

I recently finished with some user testing following the release of Zoom (I've been re-watching the recordings for the ones before break so I can compile my results). It was a very small group of advisors, but most of the folks I tested with had some confusion over the "End Meeting" wording, for the same/similar reason @ssciolla mentioned. The advisors I talked to thought of the "End Meeting" button in the same way as the trash icon in the Meeting Queue table.

**Comment by mfldavidson** [comment]
I'm ok with switching to trash icon and keeping the same language in the popup. Should I go ahead and edit the issue to reflect that @ssciolla @jlost @teshsopher ?

**Comment by ssciolla** [comment]
That works for me. Maybe just confirm with @teshsopher.

**Comment by teshsopher** [comment]
That works for me too!

**Comment by ssciolla** [comment]
@mfldavidson, I have a draft PR for this (#310), but I'd appreciate it if you could update the issue so I'm sure I'm doing everything you want related to this change.

**Comment by mfldavidson** [comment]
@ssciolla does that work?

**Comment by ssciolla** [comment]
@mfldavidson , sure, the issue title needs to be changed, but I'll do that. We may want to just review the language everywhere after the change is in place to make sure we're being consistent.

**Comment by mfldavidson** [comment]
Tested in QA 2/15 using Chrome Desktop:

- [ ] Added user for a Zoom meeting, self-assigned host, created meeting, then removed with trash icon = success ✅ 
- [ ] Added user for an In Person meeting, self-assigned host, created meeting, then removed with trash icon = success ✅
