### ISSUE TITLE
Add button to see information on joining the meeting by phone to host side

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#29]

**Comment by jlost** [comment]
@mfldavidson @teshsopher For this, I'm picturing an "Info" button to the meeting list items, like so:
![image](https://user-images.githubusercontent.com/11338926/80529002-d0bcf200-8964-11ea-9ad3-ca6c40604c17.png)
This would pop up a modal that displays dial-in info, and later could be extended to display any other relevant info, depending on the type of meeting it is (BlueJeans, Zoom, etc).

**Comment by jlost** [comment]
I'm thinking "Time Joined" could also go here.

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/80546863-bd218380-8984-11ea-836c-32aaa7ca2a30.png)
Thoughts?

**Comment by mfldavidson** [comment]
I think this implementation makes sense, good thinking. I worry that people won't know what "More Info" means but I like that it's flexible for future info. @teshsopher what do you think?

Let's also add the international call-in info here

**Comment by teshsopher** [comment]
I've changed the wording too be "Join Info," since that gives more of an indicator of what the information is. I've included it as part of my design for Issue #24, which is here: https://www.sketch.com/s/d3e8e90e-86a6-4d57-ba0e-33e40954eda9

As a note, the design still needs more testing/feedback, but this was the initial design

**Comment by jlost** [comment]
I made my implementation similar to your mockup and moved it into dev. Let me know what you think.

**Comment by teshsopher** [comment]
I think the "Action" section looks great! When the queue is empty, is it possible to add text to say, "No meetings in queue."? It's not a major problem if not, but it helps users understand what they're seeing when they see an empty queue.

As an FYI: I may have some accessibility feedback later. The Accessibility team is currently swamped, so I'll review what I can myself for now until I can get more "official" feedback

**Comment by mfldavidson** [comment]
This is coming together so nice!!! Great work you two :D 

Some thoughts/questions:
1. Should the international numbers link open in a new tab? I know we have to be conservative about using target=_blank, but I feel like it might be needed here. Navigating to a new page interrupts the process of working their queue, and also they still need to go back and get the meeting number to enter once they call the number.
2. I feel like we might want to adjust the call-in language to better accommodate the international numbers. What would y'all think of:
> As a back-up, you can call 1.312.216.0325 from the USA (or [find your international number to call in from outside the USA](https://www.bluejeans.com/numbers)) from any phone and enter 596309872#.

**Comment by mfldavidson** [comment]
Last one: Could we change the header of the popup to say "Meeting and Join Info" or just "Join Info" to match closer to what they expect when they click "Join Info"?

**Comment by jlost** [comment]
I moved all of the above changes into dev.

**Comment by mfldavidson** [comment]
@jlost the changes I requested on this were never made

**Comment by mfldavidson** [comment]
@teshsopher can you weigh in on the changes I requested in comment above?

**Comment by jlost** [comment]
^Resolved by #60
