### ISSUE TITLE
Add link to instructions on signing in to Zoom to Authorize page if authorizing Zoom

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#294]
> [Learn how to sign in to your U-M Zoom account to authorize the Remote Office Hours Queue-Zoom integration](https://teamdynamix.umich.edu/TDClient/30/Portal/KB/ArticleDet?ID=4172).

this should be an environmental variable not hard coded link

**Comment by jlost** [comment]
@mfldavidson I imagine this should open in a new tab?

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/102261150-44eddb00-3edf-11eb-9935-03b819fc8817.png)

**Comment by mfldavidson** [comment]
> @mfldavidson I imagine this should open in a new tab?

Yes

**Comment by mfldavidson** [comment]
I now realize that saying "Please click the following link" and then having a link in there that is NOT the link is confusing. Can we please change it to "Please click Authorize to allow..."
