### ISSUE TITLE
Fix non-obvious hortizontal scrolling on mobile

### ISSUE THREAD

**Issue by ksofa2** [tl-its-umich-edu/remote-office-hours-queue#298]
On phone browsers the “Meeting Actions” column in the queue manage page requires a non-obvious horizontal scroll

**Comment by ksofa2** [comment]
For example,
![Remote Office Hours Queue - Office Hours](https://user-images.githubusercontent.com/152920/102272693-27287200-3eef-11eb-839c-0ce0563f46cf.jpeg)
 on Safari on an iPhone 11

**Comment by vjcao** [comment]
May I work on this issue?

**Comment by mfldavidson** [comment]
Oh hey @vjcao ! Yes, please go ahead and work on this issue and open a PR with your work when ready. We are not actively developing right now but we can still potentially incorporate your work into a future release. Thank you so much for your interest in contributing! We really appreciate it.

**Comment by HemanginiShah** [comment]
Test Successful.  Now a gray bar shows up at the bottom window when moved horizontally

**Comment by ssciolla** [comment]
Hi @HemanginiShah, test condition should be that the scroll bar is always visible on the management page when the screen is small. This should be the case on Chrome and Safari browsers.

**Comment by HemanginiShah** [comment]
Ok, thanks for the clarification.



*With Warm Regards,**  <https://www.name-coach.com/hemangini-shah>*

 *Hemangini Shah <https://www.name-coach.com/hemangini-shah>, PMP , *BI
Analyst Senior, ITS
