### ISSUE TITLE
Add other hosts as moderators so they can record a meeting

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#3]

**Comment by jlost** [comment]
The potential solutions to this -- such as creating BlueJeans meetings "just in time" -- are very complicated and depend on completing other features first, so I'm going to move it forward in our milestones.

**Comment by mfldavidson** [comment]
I was just thinking the same thing, that's cool

**Comment by mfldavidson** [comment]
Closing this as a won't do since no new work is going to be done on the BlueJeans integration
