### ISSUE TITLE
Change queue closed message to attendees if meeting is in progress

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#300]
If the meeting is in progress, the message that attendees see if the queue is closed should change from:
> This queue has been closed by the host, but you are still in line. Please contact the host to ensure the meeting will still happen.

to:

> This queue has been closed by the host, but your meeting is still in progress. If you are unsure if your meeting will still happen, please contact the host.

**Comment by adityasadalage** [comment]
Hi, I wanted to understand whether the message should explicitly be changed to "TBD" or does the new message still need to be determined in order to set the success criteria for this issue?

**Comment by adityasadalage** [comment]
In the leave the line popup, is it sufficient to set the disclaimer as "The queue is currently closed. By leaving the queue, you will lose your place in line and will not be able to rejoin until the queue is reopened."

**Comment by ssciolla** [comment]
@adityasadalage, it sounds like you were looking at this for a class, I'm sorry we weren't more responsive earlier. I need to take this on because we're working towards a release.

**Comment by ssciolla** [comment]
@mfldavidson, can we standardize the concluding language so it's the same whether or not the meeting is in progress? I would like to do something like this:

```
      <Alert variant="dark">
          This queue has been closed by the host, but
          {props.meetingStatus === MeetingStatus.STARTED ? 'your meeting is still in progress' : 'you are still in line'}
          Please contact the host to ensure the meeting will still happen.
      </Alert>
```

**Comment by mfldavidson** [comment]
I love it. Good thinking.

I hate to add to this issue since this isn't what it's about, but it's so minor and we are here, can we tweak the last sentence as so?

```
      <Alert variant="dark">
          This queue has been closed by the host, but
          {props.meetingStatus === MeetingStatus.STARTED ? 'your meeting is still in progress' : 'you are still in line'}
          If you are unsure if your meeting will still happen, please contact the host.
      </Alert>
```

**Comment by ssciolla** [comment]
Sure, done. Please see PR #313.

**Comment by mfldavidson** [comment]
Tested in QA 2/15 using Chrome Desktop:

- [ ] Added myself to the queue while it is closed, self-assigned, then checked View as Visitor and saw message "This queue has been closed by the host, but you are still in line. If you are unsure if your meeting will still happen, please contact the host." = success ✅ 
- [ ] Back to queue management page, created meeting, then back to view as visitor and saw message "This queue has been closed by the host, but your meeting is still in progress. If you are unsure if your meeting will still happen, please contact the host." = success ✅ 
- [ ] Back to queue management page, opened queue, then back to view as visitor. Message is gone. = success ✅
