### ISSUE TITLE
Info for host on host key

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#301]
If the current user is the host of the meeting, when they click Join Info, instead of showing "You do not need a host key or participant ID" they should see "You will need to enter a host key. Find your host key at the bottom of [your U-M Zoom profile](https://umich.zoom.us/profile). DO NOT share your host key with anyone! You do not need a participant ID."

**Comment by ssciolla** [comment]
Okay, wait, to be clear, are we changing things such that a host key is required? My impression from the conversation today was that this would only be needed if you were calling in. (I just want to make sure what we're trying to accomplish, how to organize the related content.)

**Comment by mfldavidson** [comment]
No, we are not making any changes. The host key is already required if the host is only calling in on the phone, and not a computer. Maybe we should make that clear, here's adjusted language:

> You will need to enter a host key to start the meeting if you only join by calling in on a phone. Find your host key at the bottom of [your U-M Zoom profile](https://umich.zoom.us/profile). DO NOT share your host key with anyone! You do not need a participant ID.

**Comment by ssciolla** [comment]
Thanks for the clarification, @mfldavidson. I modified the language/formatting a little bit to accommodate the conditional logic. I also felt like the "if you only join by calling in on a phone" might be a bit heavy-handed given that this is already in a dial-in blurb. Can you take a look at the images below and critique my changes?
<img width="744" alt="Screen Shot 2021-01-25 at 12 37 43 PM" src="https://user-images.githubusercontent.com/35741256/105744335-f5052980-5f0a-11eb-9bec-e6e5a11b6fdd.png">
<img width="511" alt="Screen Shot 2021-01-25 at 12 38 24 PM" src="https://user-images.githubusercontent.com/35741256/105744337-f6365680-5f0a-11eb-9484-453c0908b880.png">

**Comment by mfldavidson** [comment]
Participant view looks good and I love your edits. Great work @ssciolla , let's open a PR.

**Comment by mfldavidson** [comment]
Tested in QA on 2/15 using Chrome Desktop:
- [x] confirmed that the blurb only shows up for hosts and not attendees
- [x] confirmed that the blurb matches the instructions people hear when they call in
- [x] confirmed that clicking the link to your Zoom profile works properly if currently logged into Zoom in the browser, or if not logged in; if user is logged in to a DIFFERENT Zoom account, it will show the account they are logged into and not their U-M account, but nothing we can do about that
