### ISSUE TITLE
Remove BlueJeans integration

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#302]
I believe all the changes we've made to the backends means there is little, if anything, on the frontend that needs to be done to remove BlueJeans. Please list tasks here.

**Comment by jlost** [comment]
My thoughts on the steps involved:
1. Write a script that changes all BJ meetings to Zoom meetings (this might just be a few lines in the shell)
2. Run it in dev/QA and remove BJ env vars to disable BJ. Do testing to make sure that doesn't produce any unexpected behavior, esp with existing meetings/queues
3. Add a deprecation notice that on (date) all BJ meetings will automatically be changed to Zoom meetings
4. Run the migration script and update the configuration (remove Zoom env vars) to actually disable it

**Comment by ssciolla** [comment]
There is a significant amount of BlueJeans-specifc code (the backend module), a couple BJ frontend components for dial-in info. It may be worth discussing whether these modules/components should be removed as part of this shift. It could be useful to someone else who tries to run the application, but it seems a bit silly to retain/maintain code that we aren't and don't plan on using in the future.

**Comment by jlost** [comment]
Yeah, on one hand it has some amount of value (can help other institutions, gives us a means to go back to BJ if necessary in the future, keeps the backend interface from being overfitted to Zoom). OTOH it has a definite cost in maintenance, code noise and taking up mindshare. But one of the most important consideration, and correct me if I'm wrong, is that after a certain point (when?) we'll no longer have access to BJ and our tokens will stop working, which makes it very difficult to maintain that code path going forward. It doesn't seem appropriate to retain code if we can no longer be sure it works.

**Comment by jlost** [comment]
I created #303 for details of the script.

One way we could make this changeover more gradual is by changing `DEFAULT_BACKEND` to `zoom`, which is also something we may want to give warning about.

**Comment by ssciolla** [comment]
Are we viewing this as a parent issue? From my perspective, I'm not sure anything else needs to be done beyond the work on #303 in this project/release cycle. The actual BJ-related code (the backend class -- and references to it -- and a couple front-end components) can be removed in 1.6. We can either create a separate issue and have this be the parent, or re-purpose or treat this issue as the actual removal (it does fit with the name), and move it to the next project.

**Comment by mfldavidson** [comment]
Does the script also remove BlueJeans as an option in the UI? If yes, I'm ok with using that as the issue in this project and moving this one @ssciolla

**Comment by ssciolla** [comment]
@mfldavidson, eh, the script doesn't remove it, but the PR passes info about whether backends are enabled to the frontend, which is used in the dropdowns and allowed meeting type selection UI (the available backends are filtered to those that are enabled). I'd say this is essentially what you're asking for, and that you can make a separate issue or #303 have QA testing criteria regarding this.

**Comment by mfldavidson** [comment]
That sounds like exactly what I'm asking for but maybe I'm misunderstanding?

**Comment by ssciolla** [comment]
@mfldavidson , yeah, maybe I'm mincing words. The "script" isn't doing anything to remove the option from the UI; it is now just baked into the application/UI that backends/meeting types that aren't configured won't appear as options for new meetings or allowed meetings types. The script basically cleans up the database fields to make sure the uses of the disabled backend are gone, even though they wouldn't be visible to users anyway.

I just want to make sure you consider this as part of the testing for #303. That issue title really just mentions the script, but the changes I made are broader than that.

**Comment by mfldavidson** [comment]
We had some confusion on what exactly we were considering this issue to be, but now BlueJeans is 100% removed so I'm associating this with the 1.6 project and closing.
