### ISSUE TITLE
BlueJeans -> Zoom Migration Script

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#303]
Some things that will need to be a part of this:
* Queues: If `queue.allowed_meetings` allows BlueJeans but not Zoom, remove BlueJeans and add Zoom. If it allows BlueJeans and Zoom, remove BlueJeans.
* Meetings: There are a couple directions we could go in...
    * Leave Meetings with `backend_type` of BlueJeans untouched for now and make sure the application code gracefully handles situations where a Meeting has a `backend_type` that isn't globally enabled. This has the advantage of not interrupting any final BlueJeans Meetings that were created just before BlueJeans was disabled (unlikely edge case, especially if we gave ample warning of the change).
    * Delete all Meetings with a `backend_type` of BlueJeans. This has the advantage of letting us remove BlueJeans code immediately. We will have given users ample warning that any BlueJeans meetings would be lost on (date) so it shouldn't come as a surprise.

(As I wrote the above, I think I talked myself into the "deleting the meetings" option, but lmk what you think...)

The script should return a log of all the effected queues and meetings. A dry run option would also be a good idea, just as a pre-run coherence check.

@ssciolla @mfldavidson  Thoughts?

**Comment by ssciolla** [comment]
@jlost, @mfldavidson, what do you think about instead of deleting un-started meetings with BJ, simply changing the meeting type to the default (a concept that is pretty baked into the Django backend already, and will be Zoom in the case of deployment environments)? In combination with some kind of MOTD or Alert, I think this might be the least disruptive way to handle this case. Deleting the meetings in queue would need some more messaging to handle user impact.

**Comment by jlost** [comment]
So if it's unstarted + bluejeans, change to the default, and if it's started + bluejeans, delete it. I like that and agree it could less disruptive, particularly if there are a lot of unstarted meetings of type BlueJeans when we do the migration. The only downside is that exactly what we're migrating becomes a little more conditional and thus could be harder to explain to users, or could generate some confusion if there happens to be started + bluejeans meetings.

**Comment by ssciolla** [comment]
I was actually leaning toward retaining the existing started BJ meetings for this phase of the migration, since with a little finessing they're still functional. The downside is that we may also need a way to delete them later when the backend is removed, which is more code.

**Comment by ssciolla** [comment]
I'm okay going either way with respect to started BJ meetings. Whichever way we decide to go, I think there would still be merit to retaining unstarted BJ meetings by changing the `backend_type`, as the details of the queue line are mostly maintained.

**Comment by mfldavidson** [comment]
I'd rather retain the meetings to minimize disruption but I'm happy to discuss as we discover more about what is possible. LMK when a decision is needed.

**Comment by mfldavidson** [comment]
Tested in QA 2/18/21:

### Pre-migration
- [x] Created a queue with all meeting types enabled
- [ ] Created a queue with only BlueJeans enabled
- [ ] Created a queue with only Zoom enabled
- [ ] Created a queue with both BlueJeans and Zoom enabled
- [ ] Created a queue with both BlueJeans and In Person enabled
- [ ] Created a meeting in queue with BlueJeans type
- [ ] Created a meeting in progress (started meeting) with BlueJeans type
- [ ] Created a meeting in progress (started meeting) with Zoom type

Tested both migration and deletion of BlueJeans meetings. All worked as detailed in PR--testing passed.
