### ISSUE TITLE
Change homepage text to not mention BlueJeans

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#304]
![image](https://user-images.githubusercontent.com/11338926/103808984-d0faaa80-5026-11eb-8951-230463234831.png)

This text mentions BlueJeans but not Zoom. Ideally, it should probably be sourced from the `friendly_name` of `ALLOWED_BACKENDS`.

**Comment by ssciolla** [comment]
@mfldavidson, I think you alluded to this in a recent meeting; this should probably not reference a specific VC technology at all. How about something like this?

"Join or host a queue for virtual or in-person office hours!"

**Comment by ssciolla** [comment]
You could add a line about Zoom if that's important. Something like this:

"The tool currently supports {backend.friendly_name} videoconferencing."

**Comment by mfldavidson** [comment]
How about "Join or host a queue for office hours." No mention of types?

**Comment by mfldavidson** [comment]
You could also list out the types but I balk at hard coding any specific type of meeting (like in person)

**Comment by ssciolla** [comment]
Yeah, we wouldn't need to hardcode anything if we listed the types, but I like your suggestion of not including any, as long as that's okay with you.

**Comment by ssciolla** [comment]
I guess my thinking was that the pre-login landing page should give some more specific idea of what's being offered.

**Comment by mfldavidson** [comment]
Tested in QA on 2/15 using Chrome Desktop, testing passed
![image](https://user-images.githubusercontent.com/31591389/107997518-ec0af380-6fb0-11eb-85b0-9714fa24065b.png)
