### ISSUE TITLE
Enforce Meeting.backend_type in Meeting.queue.allowed_backends via API

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#306]
We don’t seem to be enforcing that `Meeting.backend_type` needs to be present in `Queue.allowed_backends` when a meeting is created via the API. Seems like we could add another `validate` function to `MeetingSerializer` to do this. We don't allow people to do this in the UI.

There is also a question of whether we would want to prevent changes to `Queue.allowed_backends` if it involves removing a type that meetings currently use. We enforce this explicitly in the UI, but it doesn't appear to be done for the API. Enforcing this also in the API would make sense, but we would want to be careful not to disallow this globally in the backend, as that would conflict with the phasing out logic (and desire to let started meetings hang around) presented in PR #305.

This is related to #289.

**Comment by ssciolla** [comment]
Test plan

@zqian, best way to test this is probably locally via the Swagger UI. I can help get you set up, but basically you'd create a queue that only allows Zoom or in person, and then try to create a meeting via Swagger with the backend type you did NOT specify as being allowed.

**Comment by zqian** [comment]
Tested on localhost with an in-person queue. Trying to add a meeting via swagger UI for Zoom type, 
`{
  "queue": 1,
  "attendee_ids": [
    1
  ],
  "assignee_id": 1,
  "backend_type": "zoom"
}`

and got the following error in response:

`{
  "non_field_errors": [
    "zoom is not one of the queue's allowed backend types (['inperson'])"
  ]
}`

Testing is a success.
