### ISSUE TITLE
When migrating, replace disabled backend with the default backend, ignoring other enabled backends

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#317]
During discussion of the migration logic, we determined that it in the case of `['inperson', 'bluejeans']` in `Queue.allowed_backends`, it would be preferable to replace `bluejeans` with `zoom` (or some default), rather than removing the disabled backend (i.e. `['inperson']`), which is what `BackendPhaser` is doing now.

I proposed the following on Slack:

"We could replace `remove_allowed_backend` with `replace_allowed_backend_with_default` (and the implied logic, which is similar to what we have, just always add `DEFAULT_BACKEND` if it’s not present) and I think that fixes things.

Meetings would then use the default backend,  `Meeting.change_backend_type` prefers `DEFAULT_BACKEND` if it’s available."

**Comment by mfldavidson** [comment]
Tested and working in QA 2/18/21
