### ISSUE TITLE
Exception related to workers occurs with latest build

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#331]
Though the project images build fine, upon startup in the QA environment, the application throws an exception during the worker setup process, finishing with `TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>`.

This appears to be an issue related to `django/channels` and its dependency `twisted`:
https://github.com/django/channels/issues/1639

**Comment by mfldavidson** [comment]
I assume given that QA built, we can consider this tested and move to done @jlost @ssciolla please correct me if wrong
