### ISSUE TITLE
Allow admins to edit users who haven't authorized any backends

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#336]
Not super high priority but should probably fix eventually.

When attempting to edit a user in admin, such as to add or remove staff status, the form will not save if the user has not authorized any backends. The `Backend metadata` field is auto-populated with an empty dictionary `{}` and is a required field, but the empty dictionary doesn't appear to be considered content and therefore is counted as an empty field, preventing saving.

Inserting the following text into the field resolves the error and allows the form to be saved, and the user is still prompted to authorize Zoom as they normally would if the field was set as `{}`
```
{
    "zoom": {}
}
```

![image](https://user-images.githubusercontent.com/31591389/117847652-8d23e600-b250-11eb-93f2-3e334d2daf10.png)

As an admin, I need to be able to edit users who haven't authorized any backends without making adjustments to the contents of the `Backend metadata` field.

**Comment by Tombow1** [comment]
Hi! I'm new to contributions, and I want to work on this. Could you please guide me on what are some relevant files I can look at?

**Comment by Tombow1** [comment]
Hi! I'm an UM undergrad new to contributions. Could you please guide me on what are some relevant files I can look at?

**Comment by ssciolla** [comment]
Hi @Tombow1, thanks for your interest in this project! Could you please email its.tl.dev@umich.edu from UM email address? This will help us keep track of EECS student contributions, avoid issue overlap, and open another channel of communication in case you need assistance. I will take a look at your pull request over the next few work days.

**Comment by HemanginiShah** [comment]
Test 1:  leaving {} under backend metadata field under admin console for user hemashah - allowed me to see the authorize screen with step by step. Test successful.
Test 2: Leaving empty or updating with blank space in backend metadata field under admin console for user hemashah, generated blank screen and does not have any options to move to next.  This may need revisit if you believe that is not normal.

**Comment by ssciolla** [comment]
Please try testing this again next week, @HemanginiShah.

**Comment by HemanginiShah** [comment]
Hello Sam,
I was unable to test successfully due to the following issue I ran into.
I was able to land on this URL OK - https://qa.officehours.it.umich.edu/
but when I tried to login as hemashah, it gave me the system error.  So please advise what I should do.


![system error white login](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/29413657/df78d41d-c6f0-4bb4-8318-d4d8e3f9d325)

**Comment by HemanginiShah** [comment]
Testing on QA again on 6/14/23 and it worked fine.  Was able to see the authorize message after {} or leaving blank uder Admin, User, backend metadata field.
