### ISSUE TITLE
Remove "Virtual Office Hours" header from /manage

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#36]

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/81210534-0040af80-8fa0-11ea-8e75-399ec9efad5d.png)
Is this what you had in mind?

**Comment by mfldavidson** [comment]
Yes 👍 @teshsopher this ok in your book UX wise? Trying to avoid the confusion with "Virtual" vs "Remote"

**Comment by teshsopher** [comment]
It would be better to move the description text under "My Meeting Queues," if possible

**Comment by jlost** [comment]
I also changed the `h2` to h1`.
![image](https://user-images.githubusercontent.com/11338926/81410447-bc1fed00-910e-11ea-8d8c-22c954f1e4c5.png)

**Comment by jlost** [comment]
I assume this is all good - closing out.

**Comment by mfldavidson** [comment]
This also has fallen out of dev... @jlost @bruinc

**Comment by jlost** [comment]
Resolved by #61
