### ISSUE TITLE
Dockerfile does not build on M1/ARM

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#367]
On M1 Mac this fails building with the error.

```
#0 2.411       Error: pg_config executable not found.
#0 2.411       
#0 2.411       pg_config is required to build psycopg2 from source.  Please add the directory
#0 2.411       containing pg_config to the $PATH or specify the full executable path with the
#0 2.411       option:
```
Looks fixed in this issue https://github.com/psycopg/psycopg2/issues/1286

And in the latest version of psycopg2-binary

`+    'psycopg2-binary~=2.9.3'
`

**Comment by zqian** [comment]
Test was a success on my Apple M1 with `localhost` and `docker compose`
