### ISSUE TITLE
Broken INTERNAL link: Add missing favicon.ico and robots.txt

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#369]
Probably get a dozen or so messages a day about this missing file

> [ROHQ] Broken INTERNAL link on officehours.it.umich.edu
> 
> Referrer: https://officehours.it.umich.edu/
> Requested URL: /favicon.ico

**Comment by jonespm** [comment]
Some other broken links that seem to be common and are not really an error

 /static/css/srs-banner.png
/robots.txt

**Comment by Frank-duuuu** [comment]
Hi! I am reaching out on behalf of a group of students from EECS 481 Software Engineering, and we are looking for an open-source project to contribute to for our final project in the next three weeks. We are interested in your project and would love to know if we can assist in any way.

I saw this issue with the label "good first issue" and was wondering if we could provide any help. We would appreciate it if you could give us some first steps on handling this issue. Alternatively, if there is any other way we can contribute to your project, please let us know.

**Comment by ssciolla** [comment]
I see the following items needing to be resolved to close this issue:

- The missing `favicon.ico`: There is actually a `favicon.png` already in the project, so I think we just need to add a `.ico` version to make alerts about this go away. It's probably worth doing some research about whether both formats are required or recommended. I found this in a quick search: https://stackoverflow.com/questions/1344122/favicon-png-vs-favicon-ico-why-should-i-use-png-instead-of-ico
- The missing `srs-banner.png`: This file is referenced in our CSS, but I don't think it's actually present or being served. This should likely be resolved by removing the CSS that mentions it (of course, we should make sure there are no changes once it is removed).
- The missing `robots.txt`: We should add a `robots.txt`, likely "disallow"-ing or instructing bots to not scrape anything but the home page. Most of the site is behind SSO. Looks like there are some articles like this out there that would help: https://www.cloudflare.com/learning/bots/what-is-robots-txt/

**Comment by Frank-duuuu** [comment]
> Hi @Frank-duuuu, thanks for your interest in contributing to the project. I'm in contact with another student group about this issue; I'm not sure if you're part of that group or not.
> 
> Would you mind emailing our group at [its.tl.dev@umich.edu](mailto:its.tl.dev@umich.edu) and starting a conversation with us there? We can assist in finding an issue for you to work on if this one is already being taken.

Thank you so much for your offering. I have sent out the email. Hope to see you guys soon!

**Comment by ssciolla** [comment]
Test Plan

- [x] Navigate to `/favicon.ico` and see it returns the image.
- [x] Navigate to `/robot.txt` and see it returns some basic test.

**Comment by HemanginiShah** [comment]
Completed Test Plan. question on 2nd test plan item.
Navigate to /robot.txt -  I used link view-source:https://officehours.it.umich.edu/robot.txt, I need to learn how to do the basic test.

**Comment by HemanginiShah** [comment]
All listed tests in test plan successfully completed.
