### ISSUE TITLE
provide quick link to the Knowledge article on connection error

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/remote-office-hours-queue#371]
To help users deal with the known issue of connection error, we can provide the [KB article on connection error](https://teamdynamix.umich.edu/TDClient/30/Portal/KB/ArticleDet?ID=4290) inside the top info section of ROHQ home page.

**Comment by ssciolla** [comment]
This can be done with the User Comm Banner flat page with no code change, so I'm going to close this issue.
