### ISSUE TITLE
Upgrade Postgres in docker-compose from 10 to 14.4

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#381]
The operations team is going to upgrade the database to Postgres 14, they said specifically 14.4. We should upgrade our local docker-compose to match and start it up to see if anything obvious doesn't work. 

I asked if this was the latest version and it was commented that this was the latest version they saw available in AWS. Though newer minor versions may also be available soon as the most recently released is 14.7. 

Version 14 has support until November 2026. 

https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/c9a05f25c3edcc0381be424b34df0519476f798d/docker-compose.yml#L25

**Comment by zqian** [comment]
Test was a success with `localhost` and `docker compose`
