### ISSUE TITLE
Update backend dependencies

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#383]
The backend is due for an update. We're behind multiple minor versions on Python (see also #370), multiple major versions of Django Channels, and multiple major versions of Redis. Most of the other pip packages also have minor or patch versions that can be picked up, but some may need to be held back until the frontend is updated or removed/replaced due to Python/Django ecosystem changes.

**Comment by HemanginiShah** [comment]
5/31/2023: - Hi Sam, I might have to ask you to test this as I am not sure how to test this one.

**Comment by HemanginiShah** [comment]
6/16/23 - Completed QA regression test.
