### ISSUE TITLE
Platform issue when using `scripts` to push images to OpenShift

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#388]
When pushing images to OpenShift built locally, there seems to be an issue if your machine is using a new Apple M1 chip.

@jonespm noted that this can be fixed by specifying the platform `--platform linux/amd64`. He also shared this resource: https://www.docker.com/blog/multi-arch-images/

**Comment by lsloan** [comment]
If my computer doesn't have an Apple M1 processor, can I effectively QA this?  I think the implication is that even without `--platform linux/amd64`, it will always work when I use my computer with Intel processor.  Is that so?

**Comment by ssciolla** [comment]
You can test that it builds locally for you with this flag, and you could try pushing to dev. But probably also good if @zqian does it to make sure it works with M1.

**Comment by zqian** [comment]
Test was a success with `localhost` and `docker compose`
