### ISSUE TITLE
Update frontend dependencies

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#390]
The application could use some frontend updates to clear out the `dependabot` Pull Requests, bump the `node` image being used for builds and development, and generally keep the application up to date with the JavaScript/TypeScript ecosystem.

**Comment by HemanginiShah** [comment]
5/31/2023: - Hi Sam, I might have to ask you to test this as I am not sure how to test this one.

**Comment by HemanginiShah** [comment]
6/16/23 - Completed QA regression test.
