### ISSUE TITLE
Create some type of test/validation for phone numbers

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#391]
We have no way to test if the numbers that users put in are working and occasionally we've had people put in the wrong number, often adding an extra 1 at the beginning (when it's already entered for them) or just putting in the wrong value.

It could be nice if there's some way to send a "test" message or even better have a workflow where they have to validate the their phone number to use this.

Without this we get an exception when the phone is sent to. 

```
Error while sending attendee notification to 11234567890 for queue 328
1234567890
TwilioRestException
HTTP 400 error: Unable to create record: The 'To' number 11234567890 is not a valid phone number.
```

It may also be able to [use a process like this](https://www.twilio.com/blog/2016/02/how-to-verify-phone-numbers-in-python-with-the-twilio-lookup-api.html) to check if the number is valid.

**Comment by jonespm** [comment]
Sure I assigned you. If you need to open a new PR rather than pushing to their branch that's fine. If you do use code contributed by the other student please retain it as at least one separate commit on this new PR so when we do merge it the commits are retained. Thanks!

**Comment by hemashahumich** [comment]
I thought I test this in QA as I see the card.  I like to share that I entered phone 734-123-4567 and save the preference.  I did not get any error.  NOTE: 123-4567 is not my phone number.
So I would like to know what is truly detected by the newly added code to detect incorrect phone number?

**Comment by andcarls** [comment]
Did you see the process of requesting an OTP or the current deployment's method of updating numbers? If a user enters an incorrect phone number, they will not receive the OTP, and the new number will not be saved. If a phone number does not exist, and Twilio fails, it will visibly indicate the error to the user and prompt them to check their phone number. 

You should be seeing the OTP flow in #474.

**Comment by jonespm** [comment]
We were testing today and when putting an invalid number there's an exception still in the logs and it displays an empty red box to the user.

![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/27447/0bf6b92b-f1f4-4763-80e1-1e42fdc431c9)

**Comment by andcarls** [comment]
That's strange. On my local machine (all changes are checked in), it works for any Twilio errors using test credentials. See the following:
![invalid_from](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/113211908/1cc08ca9-c2fb-47db-9a3d-75222bd1210b)
![invalid_to](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/113211908/14e7b1ee-2be3-4ae8-9a5b-dfcfbe45a8f1)

It does still log the errors, I didn't suppress them in case you wanted to view the reason for Twilio's failure. I tested on the deployment, and seem to be getting a 500 server error, so it seems unrelated to Twilio. Maybe some discrepancy in local vs deployment libraries? Any info on what is executed on the backend before the exception?

**Comment by hemashahumich** [comment]
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/2dda8a7d-ff14-46a4-984d-97e3c60189c6)
Here is another test case where no meaning user message is displayed.
