### ISSUE TITLE
Bump `postgres` image version to 14.7

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#394]
We were alerted by the database team that they'll actually be using Postgres 14.7 initially. We should bump what is in `docker-compose.yml` to be consistent for local testing.

**Comment by ssciolla** [comment]
@lsloan, could you please QA this issue? Basically just build what's in `master` and try to get it started.

**Comment by lsloan** [comment]
I built the app locally, set up a superuser, logged into the admin UI, and tested the UI.  I was able to create a queue as root, create a user with my uniqname, add myself as a host to the queue, etc.  It seems to work.

:shipit:
