### ISSUE TITLE
Search queries with `/` in the name fall through React Router, end in 404

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#398]
**Expected behavior**

Search queries should be able to include special characters like `/` so that queues using these characters are properly found.

**Actual behavior**

When you search for a queue with a `/` in the name, the client-side routing doesn't catch this and it falls through to the Django app, which then throws a 404.

**Commentary**

This seems to happen even if you add `encodeURIComponent` to the lookup on the homepage (see `assets/components/home.tsx`).

**Comment by jonespm** [comment]
To reproduce just search for something with a slash like
`AC/DC`
In the search queues box.

**Comment by ssciolla** [comment]
Test cases from PR:

ssciolla
Member
[ssciolla](https://github.com/ssciolla) commented [Apr 5, 2023](https://github.com/tl-its-umich-edu/remote-office-hours-queue/pull/399#issue-1656101858) •

This PR aims to resolve https://github.com/tl-its-umich-edu/remote-office-hours-queue/issues/398. It replaces the URL parameter with a query parameter, which seems to be both better fitted to the use case (search term is dynamic, not a permanent resource) and to the HTML form element which uses it by default.

Sorry, @jonespm, I had already started working on this. Hopefully you're willing to test/review this instead.

Test setup

    Create a queue with no special characters or punctuation in the name.
    Create a queue with a "/" in the name.
    Create a queue with a "#" in the name.
    Create a queue with other special characters in the name.

Test cases

From the home page:

    Click "Search Queues" without any input. A pop-up should indicate the field is required.
    Enter a fragment of the name with the "/", including the "/". Check the queues listed to ensure the right queues are present.
    Enter a fragment of the name with the "#", including the "#". Check the queues listed to ensure the right queues are present.
    Enter a fragment of the name with special characters. Check the queues listed to ensure the right queues are present.

In the URL bar:

    Navigate to "https://localhost:8003/search/". Note that no results are returned and the search term is an empty string (undefined).
    Navigate to "[https://localhost:8003/search/?term={something}](https://localhost:8003/search/?term=%7Bsomething%7D)" where {something} is an encoded search term. Check the queues listed to ensure the right queues are present.

**Comment by HemanginiShah** [comment]
5/31/2023: Went through Test setup and all Test cases and when selected home and use search option with "/" or "#" error came back on the page with 
Page Not Found
We're sorry, the page you were looking for can't be located. If you typed in the address, you may have typed it incorrectly. If you think this is the case, please try retyping the address and resubmitting the page. If you arrived at this page from a link or bookmark, the page may no longer be available on the web. This could also be a temporary problem.

Need Help? Contact the [ITS Service Center.](http://its.umich.edu/help/)

Next tried to search using URL bar: "https://localhost:8003/search/"
Results: This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by ssciolla** [comment]
Please try testing this again next week, @HemanginiShah.

**Comment by HemanginiShah** [comment]
Hi Sam,Thanks so much will do.Regards,HemaOn Jun 8, 2023, at 3:27 PM, Sam Sciolla ***@***.***> wrote:﻿
Please try testing this again next week, @HemanginiShah.
