### ISSUE TITLE
Persistent meeting ID for owner-attendee pairings

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#4]
I found that if I keep adding myself to a queue and then taking myself off the queue, I keep getting new meeting IDs. I wonder if that is going to eventually be a problem.
Possible solution:  Reuse the same meeting ID per student for the semester since I think the meeting IDs in BlueJeans are permanent and not ephemeral. If they are one-time use only and expire, then may be the current design is fine.

--Atul Prakash

**Comment by jlost** [comment]
Looks like we can't resurrect deleted meetings in BJN, and deleting is the only way to get them out of the BJN interface.

I'm going to leave all meetings in BJN, but add a "Delete all ROHQ meetings in BlueJeans" button to the /manage interface. And add a note to all create BJN meetings explaining how to do that.

This ended up being very complicated, but "Delete all ROHQ meetings in BlueJeans" seems really feasible and will be a useful feature we should add... (See: 'Delete all ROHQ meetings in BJ')

**Comment by mfldavidson** [comment]
Based on @ksofa2 comments I am going to close this as a "won't fix" but hopefully we can implement #19
