### ISSUE TITLE
Remove warning from `validateString`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#413]
https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/9a183fb140406f9c2c0dddd82b67272922126814/src/assets/src/validation.ts#L89-L91

I thought this was a good addition in #405, but I forgot that this would trigger every time if we don't pass `showRemaining` as `true`, this would always be triggered. This happens with uniqname entry (we don't show remaining there, but we do have a `maxLimit`). We could add a separate check to see if both `showRemaining` is `true` and `maxLimit` is `undefined`, but we could also just remove this message since we control usage of this function and we don't use it this way.

**Comment by ssciolla** [comment]
Test plan

Look at the web console when using the uniqname fields on a queue management page or Settings page under Manage Hosts, and ensure that no warnings occur.

**Comment by zqian** [comment]
This is the error message when user typed in <3 chars for the uniqname field.

![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/359944/188d08c1-3e3a-4c59-bcae-f691821aeff2)

Verified the above warning message no longer shows up in the ROHQ QA server
