### ISSUE TITLE
Issue with Websockets/redis/channels in deployment

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#416]
Once we deployed to QA, we started seeing lots of timeouts, and websocket connections loading slowly or not at all. I think this is fallout from #383, but I'm not absolutely certain.

We'll need to try bumping or going back on some library versions, unless we find there is a configuration issue (hopefully not, since I don't see much in the way of warnings).

Some errors we're seeing:

```
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x561499ceb4a0>; the handler is closed
```
and
```
redis.exceptions.ConnectionError: Error while reading from officehours-redis-qa:6379 : (104, 'Connection reset by peer')
```

**Comment by zqian** [comment]
No above errors found inside the archived and current logs for both redis and web applications.
