### ISSUE TITLE
Use OpenShift namespace for build process

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#418]
Currently our approach to circumventing the Docker Hub pull limit is to use the scripts under `scripts` to build locally and push to the registry. This works OK for the web service, but we lose some metadata from building this way. The bigger issue is that we don't build `redis` locally, so we are still seeing that rate limit affecting that service when go to deploy.

At this stage, I think it makes sense to just switch to the recommended practice of using the `openshift` namespace. This would involve using `docker-registry.default.svc:5000/openshift/` as a prefix in the service YAML for `redis` and creating a separate `Dockerfile.openshift` and referencing that in the build configuration YAML for the web service.

**Comment by ssciolla** [comment]
Test plan

Look at the build history in Dev and QA and see that they are pulling from the Openshift namespace.

**Comment by zqian** [comment]
Verified the existence of "docker-registry.default.svc:5000/openshift" in the build log file.
