### ISSUE TITLE
Handle string in URL parameters that pass through React Router

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#422]
This is related to but a bit beyond #236. 

Currently, if the user enters a string in the URL parameter for queue ID, the tool will throw an error in the backend, a Queue Connection will appear in the UI, and `NaN` will appear in the breadcrumbs. This likely also affects `manage` URLs, so the solution should be reusable if possible.

After checking with the service owner, here are the suggested/desired changes:

- Change the breadcrumb text to display the incorrect string or integer value entered, not the `NaN`
- Change the error message to `Oops! It looks like you've entered an invalid queue ID <copy entered str value from URL>in the URL. Please make sure to enter the correct numeric queue ID. You can find the accurate queue ID in your 'Manage Queue' list for reference.`
- Sample changes apply to the `manage` URLs

**Comment by ssciolla** [comment]
We should also look at whether this can be enforced more cleanly in the backend.

**Comment by Nyu10** [comment]
I would like to tackle this issue

**Comment by jaydonkrooss** [comment]
This fix is properly handled in QA environment. moving to completed.
