### ISSUE TITLE
Remove icon not correctly placed in list of queue's hosts

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#425]
I noticed a visual bug that fell through the cracks during #405. For any host list items past the first one in the Manage Hosts tab in queue settings, the host's name and the remove icon will be jumbled together, instead of having the remove icon floating to the right as in production. This is because in Bootstrap 5, utilities changed to using `start` and `end` over `left` and `right.

![Screenshot 2023-06-14 at 3 38 48 PM](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/35741256/c782a9d9-131e-409b-ba42-8fb37ab29d21)

I should also do a quick search for `-left` and `-right` to make sure I didn't miss any other instances of this.

**Comment by ssciolla** [comment]
Test plan

- [ ] Ensure that the logo image in the top navigation bar looks the same in QA as in production at a few different window sizes.
- [ ] When looking at multiple hosts under Manage Hosts under your queue's Settings, ensure that the remove (trash) icon is to the far right of the box for each host that is not you (instead of under).

**Comment by HemanginiShah** [comment]
Test successful
