### ISSUE TITLE
Use specific `slim-bullseye` version of Python base image

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#427]
Because of a change in Python's `-slim` image from `buster` to `bookworm`, we started having build issues yesterday in the Openshift 3 cluster. We need to specify `python:3.10-slim-bullseye` to get this to build correctly.

**Comment by ssciolla** [comment]
Test plan

Look at the build history in QA to see how previous builds using `python:3.10-slim` failed, and then either rebuild yourself or look at other builds done after this commit.

**Comment by zqian** [comment]
Verified from the build history of QA server:
- previous build failed with `docker-registry.default.svc:5000/openshift/python:3.10-slim`
- the current build succeeded with `docker-registry.default.svc:5000/openshift/python:3.10-slim-bullseye`
