### ISSUE TITLE
Suppress `redis` log messages about failed writes to disk

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#429]
After upgrading to `redis:7`, we are seeing some additional logging messages in the `redis` service container on OpenShift like this:

```
Background saving started by pid 477
Failed opening the temp RDB file temp-477.rdb (in server root dir /data) for saving: Permission denied
```
This is almost certainly because we have not given the user permission to write to `/data` or mounted a volume for the writing to occur. The deployment YAML was already specifying an option to disable "stop-writes-on-bgsave-error", which seems to indicate that writes (to disk) were not working before either.

After discussing with @jonespm, it seems like it would be safe to disable writing entirely using the `save` setting with an empty string. Or we could add a volume, but I think the main purpose of the background saving would be to recover important data. My understanding of channels and its usage of redis is that any connection data would just be reestablished if it was lost in a disaster.

Resources
- https://redis.io/docs/management/persistence/
- Default `redis-conf`: https://raw.githubusercontent.com/redis/redis/7.0/redis.conf

**Comment by ssciolla** [comment]
Test plan

After QA has been running for a while with some activity, check that the `redis` container/pod does not have the above errors.

**Comment by zqian** [comment]
the redis container log is pretty clean without the above mentioned error message.
