### ISSUE TITLE
Meeting update throwing Internal Server Error

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#432]
https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/e0c8276f2f323bbc16888af094100f77f4bda7c1/src/officehours_api/views.py#L189-L193

It looks like I neglected to return the response when calling update in the `try` clause. This is causing an internal server error to be thrown whenever a meeting is patched (update) by the attendee or host.

**Comment by HemanginiShah** [comment]
Error is not appearing any more.
