### ISSUE TITLE
Improve UX of Add Queue workflow

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#438]
@janelilr from the DUX team provided two suggestions for the Add Queue workflow to improve clarity or usability.

1) On the General tab
    Current: “*indicates a required field”
    Suggestion: “*Required Field”
    Reason: provide a concise text
    Cosmetic issue

2) Manage Hosts tab
    Current: “Back” button and “Finish Adding Queue” button are the same color 
    Suggestion: Identify which button is the primary button and assign it a color. The other button would be the secondary button and it can be a button outline.
    Reason: helps focus what the main button is
    Minor usability issue

**Comment by HemanginiShah** [comment]
Back button takes you back previous page without losing the info.  Works!
