### ISSUE TITLE
"Return to Previous Queue" button does not work from another queue

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/remote-office-hours-queue#445]
**Expected Behavior**

When currently in line in one queue, if you visit another queue, you should see an alert saying you are already in line and be able to click a "Return to Previous Queue" button to return to the other queue.

**Actual behavior**

Clicking the "Return to Previous Queue" button does not make the page re-load, though it does change the URL. See the video below.

Note that this does not affect the "Return to Previous Queue" button that appears conditionally on the home page.

https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/35741256/8f884461-4ebe-4698-ba5c-3606ee0cafd3

**Commentary**

This behavior seems to have been a side effect of updating React Router Dom and changing from a props approach to a [`useParams`](https://reactrouter.com/en/main/hooks/use-params) approach. I'm not entirely sure why the behavior changed, but I tested with 1.7.0 and the behavior is not present. The solution seems to be modify `useWebSocket` so that the internal `useEffect` retriggers if the URL (using the queue ID) changes. I think it wasn't re-rendering because the `useEffect` has no dependencies and the page component itself isn't being re-loaded (just the param changes). Could be off on that.

**Comment by zqian** [comment]
FYI, if the user clicks on the the "Remote Office Hour Queues" link to get back to the home page, the "Return to Previous Queue" link works there.

**Comment by ssciolla** [comment]
> FYI, if the user clicks on the the "Remote Office Hour Queues" link to get back to the home page, the "Return to Previous Queue" link works there.

Yep, I mentioned that above.

**Comment by hemashahumich** [comment]
I am unable to move this card to Done column in the project.  Please move it for me.
