### ISSUE TITLE
Create packages and builds on Github

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#454]
Now that we can use Github for storing packages, we should use the same pattern as created for MyLA to store packages in this repository. This would help for the releases and also reduce the chance of any build problems on Openshift. 

This workflow can probably be modified to support this repository. https://github.com/tl-its-umich-edu/my-learning-analytics/tree/master/.github/workflows

**Comment by lsloan** [comment]
Package is available in repo, as shown on "Packages" page:  https://github.com/tl-its-umich-edu/remote-office-hours-queue/pkgs/container/remote-office-hours-queue

Most recent package is tagged `master`: https://github.com/tl-its-umich-edu/remote-office-hours-queue/pkgs/container/remote-office-hours-queue/298374590?tag=master
