### ISSUE TITLE
Newlines & whitespace in REDIS_HOST cause connection errors

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#458]
It's relatively easy to create a REDIS_HOST file that has a newline in it. It would probably be nice if the code stripped this value out, just calling .strip() on the value. 

https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/582957e2a9530be8ec902ef2dac518e3bcee0e29/src/officehours/settings.py#L316C20-L316C20

**Comment by Leonard6261** [comment]
Hi, @jonespm. I am a student at EECS 481, and I would like to claim the issue! Also, I would write a unit test for this to test changes we made.

**Comment by jonespm** [comment]
Okay I assigned you to this. I don't know if this class has any specific tests for the settings yet but sure you could add one!

**Comment by zqian** [comment]
The REDIS_HOST settings on test, qa and prod servers contain no whitespace characters.
