### ISSUE TITLE
Switch Zoom code over to use the package 

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#466]
The Zoom code we have here is all custom and may be difficult to maintain in the future. There is a [well maintained package in PyPi](https://pypi.org/project/pyzoom/) that we may want to consider using if we want to make any changes to this.

**Comment by peijli** [comment]
Has this feature been implemented yet? If not, I, together with my collaborator @Leonard6261 in the U-M EECS 481 course, would like to help out by claiming this issue.

**Comment by JosephFak** [comment]
If the previous commenter is unable to work on this would I be able to claim this issue?

**Comment by jonespm** [comment]
Hi! Thanks for the interest on this issue. I'm not entirely sure if you'd be able to test this issue with your own account but it probably would work with the OAuth flow. 

The original file has a lot of code for doing what the library does and is 250 lines total so I'm expecting this would be a lot less. I'm estimating it could take a full day of effort to get this working. I'll assign @peijli to it since they mentioned it first and not sure what happens if two groups work on the same task.

**Comment by zqian** [comment]
@peijli do you find a way to get the zoom client id and secret to get this going?

**Comment by peijli** [comment]
Still working on it. We hope to get something going over the next week.

**Comment by zqian** [comment]
Sorry, @peijli. We cannot provide zoom client secrets.

**Comment by peijli** [comment]
Pull request for this issue: https://github.com/tl-its-umich-edu/remote-office-hours-queue/pull/481

**Comment by jonespm** [comment]
This was reverted but we still want to have this fixed. We need to remember to check that meetings can be created and after the zoom token expires it can be refreshed. It gave an error about refresh in this release.
