### ISSUE TITLE
Reporting download link options

### ISSUE THREAD

**Issue by hemashahumich** [tl-its-umich-edu/remote-office-hours-queue#470]
We need to determine the most effective way to provide queue-level information to individual queue owners. One option we discussed is to include a reporting link either under the "Manage Queue" page or at the top pulldown option next to the login name top right corner. Additionally, we could consider placing a link in a column preceding or following the status column for each queue. For instance, we could incorporate a download button on the individual queue details page, accessible to anyone with queue management privileges. This would allow for easy access and utilization of the reporting feature.

I will let you decide on the easiest way to implement this feature.

**Comment by OscarSong2003** [comment]
Hey, I'm a current student in EECS 481 who is looking to contribute. Wondering if I can potentially contribute to this task? Thanks!

**Comment by zqian** [comment]
@OscarSong2003 Thanks for your interest. However, this issue may need more efforts and may not be an ideal candidate for your EECS 481 assignment. 

Instead, please choose from those open issues with the label [Good First Issue](https://github.com/tl-its-umich-edu/remote-office-hours-queue/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)

**Comment by zqian** [comment]
will access whether this is still needed once #97 is implemented

**Comment by hemashahumich** [comment]
Sounds good to me.

**Comment by hemashahumich** [comment]
Thanks so much Jaydon.  I have added the test cases to the Release
Plan/test file:
https://docs.google.com/spreadsheets/d/1JZUKW2WCPPPJccGXcCM1cNm8Ksv5DaNTnUzDpEbxCK0/edit?gid=1624795005#gid=1624795005


<https://docs.google.com/spreadsheets/d/1JZUKW2WCPPPJccGXcCM1cNm8Ksv5DaNTnUzDpEbxCK0/edit?gid=1624795005#gid=1624795005>


*With Warm Regards,**  <https://www.name-coach.com/hemangini-shah>*

*Hemangini Shah <https://www.name-coach.com/hemangini-shah> *She/Her/Hers*, PMP
, *BI Analyst Senior, ITS

Manages Services: Student Success Viewer
<https://its.umich.edu/academics-research/teaching-learning/student-success-viewer>
, Remote Office Hour Queue
<https://its.umich.edu/communication/videoconferencing/remote-office-hours-queue>
, Canvas/NameCoach
<https://its.umich.edu/academics-research/teaching-learning/namecoach>,
Canvas/Perusall
<https://its.umich.edu/academics-research/teaching-learning/perusall>

**Comment by hemashahumich** [comment]
"1. Queue name is not appearing in downall all history button download csv file.  
2. Deleted queue are not getting listed. 
3. Can we get that to downloaded
Currently, the reporting button ""Download"" and the ""Download All Queue History"" are tracked based on the signed-in user.  Question: Should the admin or service manager have access to view the Download button or download all queue history button for a single queue and for all queues?"
