### ISSUE TITLE
Message of the Day

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#48]
Currently there is a banner whose message changes depending on whether or not DEBUG is enabled:

![image](https://user-images.githubusercontent.com/11338926/82076288-9e70fb80-96ab-11ea-8c33-a350d58beca4.png)

Use [Django Flatpages](https://docs.djangoproject.com/en/3.0/ref/contrib/flatpages/) to make this content editable via the Admin panel. The idea is that different environments could configure it with different messages, and/or news updates could be put here, such as "latest features" after an update is released.

**Comment by jlost** [comment]
Closed by #49

**Comment by mfldavidson** [comment]
I don't see this has been QA tested yet, hence moving back to QA

**Comment by jlost** [comment]
Feel free to test it - I moved it forward because the changes are effectively non-user-facing, as the markup you put in the "User Comm Banner" flatpage can be the same as the current markup in prod.

**Comment by mfldavidson** [comment]
So I did some testing, and I learned the following:
1. the Advanced Option of "Registration Required" causes the banner to not be visible to anyone--maybe not properly hooked up to the auth?
2. The "Sites" box is not set up--it just says "example.com" but doesn't seem to impact anything
I don't think these are blockers to releasing but...just worth a note
