### ISSUE TITLE
Remove Twilio requirement for local build

### ISSUE THREAD

**Issue by jaydonkrooss** [tl-its-umich-edu/remote-office-hours-queue#487]
When running the app locally without having set up Twilio credentials, the following error appears:
```
twilio.base.exceptions.TwilioException: Credentials are required to create a TwilioClient
``` 

Analyzing the traceback, it appears that code referencing Twilio credentials was added to `notifications.py` (line 17) in a recent PR #474, so the code should be rewritten in order to allow for skipping the credentials if they don't exist.

**Comment by zqian** [comment]
@jxiao21 can test this
