### ISSUE TITLE
User preferences Phone number bugs

### ISSUE THREAD

**Issue by jaydonkrooss** [tl-its-umich-edu/remote-office-hours-queue#497]
Address multiple regressions between QA and production on the user preferences page, where users can save and edit their phone information & text messaging preferences. Most likely introduced in PR for #391, so find out if some or all of these bugs can be addressed:
- clearing (backspace) and saving the empty phone number shows "your preferences were not saved" in QA. In production, does this properly remove the phone number for the user?
- unchecking "I want to be notified via SMS" shows preferences not saved - investigate how checking checkboxes gets saved 
- trying out an invalid number created an empty warning message

**Comment by hemashahumich** [comment]
I removed the phone number via backspace and clicked save button.  It displayed message "Your preferences were not changed."  See the screenshot below:
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/11ea3c70-c1f4-4ccc-b2a1-aff62925628c)

=========
I re-enter the same phone number & get the following message: 
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/83fadc4b-c6bd-41a1-9921-429235581a4e)

======================
After I selected the one of the checkbox I get the following message to appear: 
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/2655ec94-01dd-46e8-9840-f1fe3821b14f)

==========================
I unchecked both boxes and clicked on save and I get the following message appear which does not seem right.
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/32ee8c68-3dfd-47aa-80cf-a0ec93e4c316)

==================
I updated the number to not legit number and clicked on save and I get the following message to appear:
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/e8b24e06-123e-46e8-b000-d762c945b08e)

**Comment by hemashahumich** [comment]
### Additional Information on the Preferences Test Cases

1. **Alert Message When Removing Phone Number:**
   - **Steps:**
     1. Remove the previously saved phone number.
     2. Without selecting or updating any checkboxes, click the "Save" button.
   - **Expected Result:**
     - The message displayed should be: "Your preferences were successfully updated." 

2. **Alert Message When Adding New Phone Number:**
   - **Steps:**
     1. Update the phone number to +1 (555) 555-5555.
     2. Without selecting or updating any checkboxes, click the "Save" button.
   - **Expected Result:**
     - The message displayed should be: "Your preferences were successfully updated."

3. **Alert Message When Updating with Same Phone Number:**
   - **Steps:**
     1. Update the phone number to the same format, e.g., +1 (xxx) xxx-xxxx.
     2. Without selecting or updating any checkboxes, click the "Save" button.
   - **Expected Result:**
     - The message displayed should be: "Your preferences were successfully updated."

4. **Alert Message Appears to Work When Updated with Checkboxes:**
   - **Steps:**
     1. Select one of the checkboxes or both
     2. system checks if the phone number exists, if yes
     3. Click the "Save" button.
   - **Expected Result:**
     - The message displayed should be: "Your preferences were successfully updated."

5. **Alert Message Appears to Work When Updated with Checkboxes:**
   - **Steps:**
     1. Select one of the checkboxes or both
     2. system checks if the phone number exists, if phone number field is blank
     3. Click the "Save" button.
   - **Expected Result:**
     - The message displayed should be: "You must enter a phone number to opt in to host SMS notifications."

**Note:** The message "Your preferences were successfully updated" appears to work correctly only when a checkbox is updated. It does not work correctly when only the phone number is updated.

**Comment by hemashahumich** [comment]
@jaydonkrooss I noticed a typo in #3 under test cases and have made update to the message that displays when no changes to phone number or check boxes are made.

**Comment by hemashahumich** [comment]
@jaydonkrooss 
Given the recent changes, it's prudent to consider whether any adjustments are needed for the current prod version of the test cases listed in rows 45-51 of the [1.10 Full Test Plan](https://docs.google.com/spreadsheets/d/1JZUKW2WCPPPJccGXcCM1cNm8Ksv5DaNTnUzDpEbxCK0/edit?gid=1624795005#gid=1624795005). If updates are required, we can proceed in two ways: 

1. You can review and update the necessary changes to any or specific test case  or 
2. I can take the lead in updating the test cases, with you providing the impacted test cases required changes and I will make the update

This ensures that our Quality Assurance (QA) process, both pre and post, includes thorough verification aligned with the recent changes. 

Let me know which approach you prefer or if there are any specific details you'd like to discuss further.

**Comment by jaydonkrooss** [comment]
@hemashahumich I will try to release the changes on the ROHQ dev instance so that you can start looking at the test cases. I think it'd be best if I could just show you the changes first, before you make the updates to the test cases as you see fit

**Comment by hemashahumich** [comment]
@jaydonkrooss That sounds good.



*With Warm Regards,**  <https://www.name-coach.com/hemangini-shah>*

*Hemangini Shah <https://www.name-coach.com/hemangini-shah> *She/Her/Hers*, PMP
, *BI Analyst Senior, ITS

Managing Services: Student Success Viewe
<https://its.umich.edu/academics-research/teaching-learning/student-success-viewer>
r, Remote Office Hour Queue
<https://its.umich.edu/communication/videoconferencing/remote-office-hours-queue>
, NameCoach
<https://its.umich.edu/academics-research/teaching-learning/namecoach>,
Perusall
<https://its.umich.edu/academics-research/teaching-learning/perusall>

**Comment by hemashahumich** [comment]
@jaydonkrooss 
Hello Jaydon,
While testing, I noticed that if we delete a phone number, save the changes, and then re-enter the same number, it prompts for verification again. To address this, we might want to update the alert message to say: "This phone number has been verified and saved. No re-verification is required at this time.".  Please let me know if you have any questions.

**Comment by jaydonkrooss** [comment]
The changes were already tested in canvas dev, so I'm moving this issue to Done.
