### ISSUE TITLE
Upgrade Django version to 4.2

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#503]
Django 3.2 recently end EOL, so we should upgrade the backend to Django 4.2. This would include upgrading other related dependencies such as channels and other django-* packages.  

Django Channels 4.1.0 supports a new "reason" parameter to the close method which could allow passing additional information into the frontend to make some error messaging more specific for the 4404 and other similar errors passed into `useWebSockets`.

**Comment by zqian** [comment]
Tested basic functions including Twilio and Zoom integrations on QA server. No critical alerts on Docker hub.
