### ISSUE TITLE
Add proxy model to prevent migration of view

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#529]
Django is trying to migrate a view that was manually created, we should add a proxy model so it won't try to manage this. The alternative looks like might be a SAVEPOINT but this seems the best.

**Comment by jonespm** [comment]
To QA this just look at the logs and make sure there aren't any migrations waiting.

**Comment by zqian** [comment]
The QA log shows:

'Running migrations:
No migrations to apply.
Your models in app(s): 'officehours_api' have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.'

**Comment by jonespm** [comment]
Okay it looks like that error is related to this bug I just filed. #574

I thought it would be fixed by the Bluejeans removal but it requires more work. I don't think it's a blocker for this release and we'll just ignore the message until next release when this should all be cleaned up. We likely need to move this field out of the model and into the API and I wouldn't delay the release for that.
