### ISSUE TITLE
Increase contrast for Login button on homepage

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#53]
Given we have removed the container on the homepage to support #35 the Login button that a user sees on the homepage content area now needs to have more contrast between the button and the background.

@teshsopher feel free to comment with any particular input on how to implement this

![image](https://user-images.githubusercontent.com/31591389/82464819-8246d300-9a8c-11ea-8b5b-dfcefae45ddf.png)

**Comment by teshsopher** [comment]
There isn't necessarily a specific color that it should be, though a blue would fit the general style of U-M and the app (though other colors have been used before!). However, the contrast ratio for the button and the background (but also the text and the button) should be 4.5:1 at minimum. In an ideal scenario, the contrast should be 7:1.

**Comment by bruinc** [comment]
Thoughts on these?

![btn-primary](https://user-images.githubusercontent.com/23128544/82491688-fa27f400-9ab2-11ea-9f3a-532a09ce0e7e.png)

![dark blue back](https://user-images.githubusercontent.com/23128544/82491702-fdbb7b00-9ab2-11ea-9d78-a7e8a3cdbe4a.png)

**Comment by mfldavidson** [comment]
I defer to @teshsopher as the expert but I think the first one, slightly lighter, makes sense, and matches the color of the "Search Queues" button that shows up in the same space once the user is logged in

**Comment by mfldavidson** [comment]
Either seem to have the right contrast though

**Comment by teshsopher** [comment]
The first one works for me as well!
