### ISSUE TITLE
Return & handle 502 from BlueJeans 500s

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#54]
If BlueJeans returns a 500-level error, return a 502 (Bad Gateway) to the front-end. In the front-end, display a message clarifying that something went wrong in BlueJeans.

**Comment by jlost** [comment]
@teshsopher @mfldavidson  Added the following message, mainly to help quickly identify the source of the problem when BlueJeans outages occur:
![image](https://user-images.githubusercontent.com/11338926/82681060-324a4680-9c1b-11ea-9342-e9076248a66c.png)

**Comment by teshsopher** [comment]
Does this happen with a specific error? Also, is there a specific action the user can take to fix what went wrong themselves? The error is kind of vague (which it may need to be), but having some text to let the user know what steps to take next would be helpful

**Comment by jlost** [comment]
It happens for any error coming from BlueJeans, which could be a number of things on their end, which we have no visibility into. The only thing they could do is contact 4help and/or try again later.

**Comment by mfldavidson** [comment]
I would suggest adding the following text after the current message, would like @teshsopher input:

> You can <a href="https://status.its.umich.edu/">check the ITS Status page</a> to see if there is a known issue with BlueJeans, or <a href="https://its.umich.edu/help">contact the ITS Service Center</a> for help.

**Comment by teshsopher** [comment]
I think that sounds good to me

**Comment by jlost** [comment]
For now I can only put plain text in the error alerts. We can enrich them in the next release. For now, I'll have to do: 
>You can check the ITS Status page (https://status.its.umich.edu/) to see if there is a known issue with BlueJeans, or contact the ITS Service Center (https://its.umich.edu/help) for help.

**Comment by jlost** [comment]
This one is tricky to test in dev. This is what it looks like when I force it locally:
![image](https://user-images.githubusercontent.com/11338926/83299600-7eb9f700-a1c4-11ea-9cdd-24b1cff395fe.png)

**Comment by jlost** [comment]
The capitalization (Bluejeans vs. BlueJeans) is a little off, because I wanted the message to be generic for different backends (Zoom) and the backend names are lower-cased. The "best fix" would be to attach a "display name" property to backends, but that work is better saved for the next release I think.

**Comment by teshsopher** [comment]
The message is a little long (since we can only use plain text), but I think it works well enough for this release. I'll think about if there is a better way to word this in the meantime

**Comment by jlost** [comment]
I see I also missed a space after the first period, so I fixed that.
