### ISSUE TITLE
Handle BlueJeans User 404

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#55]
If the BlueJeans /user endpoint returns a 404, a message should appear in the client telling the user they must log into BlueJeans before using Office Hours.

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/82678281-560b8d80-9c17-11ea-9ee0-20e0675face4.png)
@teshsopher Thoughts on the message? Because of the way errors are propagated from the server to the client, it would take a fair amount of extra work to include anything other than plaintext there (such as a link to umich.bluejeans.com). We could revisit this next cycle and explore more in-depth fixes (maybe it's possible to create a user for them).

**Comment by teshsopher** [comment]
For this solution, it may be better to say "There is no BlueJeans account associated with [user email]. Please log into umich.bluejeans.com, then try again." That way, users know what the error means, as well as what to do about it. (Though, if I'm misunderstanding what the error means, please correct me!)

**Comment by jlost** [comment]
Changed it to exactly that:

![image](https://user-images.githubusercontent.com/11338926/83163077-97e57980-a0d8-11ea-83b4-0f040500b8a6.png)

**Comment by mfldavidson** [comment]
I tested this with my sponsored account zoomz.
1. created queue https://dev.officehours.it.umich.edu/manage/63 -- everything fine, no error
2. added someone to the queue manually and got the error
![image](https://user-images.githubusercontent.com/31591389/83281315-e4e35180-a1a5-11ea-9afb-8c6d356ad3f2.png)
3. joined someone else's queue https://dev.officehours.it.umich.edu/queue/47/ successfully

So I think we can call this tested!
