### ISSUE TITLE
BadHeaderError if EMAIL_SUBJECT_PREFIX has newlines

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#559]
If EMAIL_SUBJECT_PREFIX contains newlines in the config there's an error like this one which makes debugging impossible.

`django.core.mail.message.BadHeaderError: Header values can't contain newlines (got '[TEST_ROHQ] \nERROR (EXTERNAL IP): Internal Server Error: `

While we can change this config, the code should ensure that this is value has newlines removed.

**Comment by jonespm** [comment]
Adding this to 1.12.0, it's a simple fix but it's also fixed by having a correct configuration file which we have control over.

**Comment by jadfalaoui** [comment]
Hello, I would love to work on this issue in the context of my final assignment for EECS 481: Software Engineering. Please let me know if this error is still occurring in the latest build!

**Comment by jonespm** [comment]
Hi @jadfalaoui, yes this is still an issue and probably an easy fix similar to #473. 

That issue even added a test case but it didn't check for this case.

**Comment by jonespm** [comment]
Re-opening as it was mentioned there's an error if `EMAIL_HOST `is not set as there is a None default. I tested with these values being set.

There's probably a few ways to fix it, the first that comes to mind to keep it None would be to check first
`EMAIL_HOST = os.getenv('EMAIL_HOST').strip() if 'EMAIL_HOST' in os.environ else None`

I'm also happy iwth Django's default of `localhost` which is probably more straightforward so just
`EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost').strip()`

**Comment by zqian** [comment]
Verified no newlines inside the EMAIL_HOST settings on dev, qa and prod servers

**Comment by jonespm** [comment]
Hi @JayeshVelivela, this issue had a PR submitted and accepted last year. You'll have to look for another open issue.
