### ISSUE TITLE
Zoom meetings created without dial-in permission

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/remote-office-hours-queue#573]
While helping @HemanginiShah with testing, we tried this test on row 155 of the testing sheet (https://docs.google.com/spreadsheets/d/1DiFZNtC4B7v7Yw7sf6AY7PR73nWQWr8GMdIcgjwAtDU?gid=1581036365#range=155:156)…

Later I will clean up the table below, but to summarize:  It seems that the Zoom meeting created for my queue doesn't allow dial-in.  The link for dial-in worked, but ultimately I was not able to connect to the meeting.

f | Links(be mindful of environment you're testing in) | Task | Success Criteria(Note links--if doing pre-release testing, test in QA, if doing post-release testing, test in prod) | Likely affected by release | Pre-release Testing Passes (initials) | Post-release Testing Passes (initials) | Notes
-- | -- | -- | -- | -- | -- | -- | --
View Queue as Visitor (your own queue) | N/A | IF TESTING ON MOBILE ONLY (if not, skip this task)Click the number hyperlink | Your phone dials 1.312.626.6799 and then enters the meeting ID at the appropriate time without you doing anything. You end up in the meeting (likely waiting for host to start) without having to enter anything on your keypad except maybe a pound key. | NO | No (Mr. Lance E Sloan (UMich)).  See my notes in the "Notes" column, |   |  
  |   |   |   |   | Issue to be created by Lance for the backlog.  It will be addressed in the future release |   | Mr. Lance E Sloan (UMich) 10/30/2024: Following the directions closely, viewing a queue I manage as a visitor, I joined the queue, then added a meeting, then clicked on the phone number link.  The instructions didn't say so, but my phone required me to choose which phone app to use.  Once that phone app started, I had to click on the dial button to begin the call.  Once connected, there were pauses while the meeting ID was dialed.  After the ID was entered, Zoom phone service spoke the error message, "this meeting does not allow phone dial-in".  It appears the meeting was not created correctly. -  Mr. Lance E Sloan (UMich) Lance good to know this, I just didn't know how Jason captured the screenshot and successfully completed the test.

**Comment by jonespm** [comment]
Fixed by #575
