### ISSUE TITLE
Zoom meetings created with wrong settings

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/remote-office-hours-queue#575]
Zoom meetings are being created without permission for users to join via phone audio only (dial-in).  The problem comes from [lines 145–154 of /src/officehours_api/backends/zoom.py](https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/50bd2ac/src/officehours_api/backends/zoom.py#L145-L154)…

```python
        # Specify the meeting settings
        # We are initializing the meeting settings with the default settings
        # and then modifying the settings we want to change
        meeting_settings = ZoomMeetingSettings.default_settings()
        meeting_settings.waiting_room = True
        meeting_settings.join_before_host = False
        meeting_settings.meeting_authentication = False
        meeting_settings.use_pmi = False
        meeting_settings.contact_name = user.first_name + ' ' + user.last_name
        meeting_settings.contact_email = user.email
```

The `pyzoom` module's default setting for `audio` is `voip`.  The API documentation explains the values of this setting as…

```
audio
enum
Determine how participants can join the audio portion of the meeting.
both - Both Telephony and VoIP.
telephony - Telephony only.
voip - VoIP only.
thirdParty - Third party audio conference.
Default: both
Allowed: both┃telephony┃voip┃thirdParty
```

We need to use the `both` value for the setting or possibly no value at all and let Zoom use the default, which also is `both`.

We also need to check the other setting values obtained through `default_settings()`.

**Comment by HemanginiShah** [comment]
Lance and I successfully tested the audio dial-in scenario and logged in as an attendee while you hosted. The single sign-on to Zoom worked well.
