### ISSUE TITLE
Confirm Zoom account and app integration

### ISSUE THREAD

**Issue by bruinc** [tl-its-umich-edu/remote-office-hours-queue#58]
As part of the setup flow, we should check if a host has a Zoom account and has enabled the ROHQ app. If not, instruct them to do that and do not let them continue until they have.

**Comment by mfldavidson** [comment]
Great idea, I completely agree!!! 👏

**Comment by mfldavidson** [comment]
Edited to reflect Zoom since we aren't doing new work on BlueJeans

**Comment by jlost** [comment]
Technically done in #129 but there is still some polishing to be done on the implementation. I'll create a new issue for that.
