### ISSUE TITLE
Feature: Have a separate field in which the student can enter alternate contact information (e.g. email, cell phone #, etc.) if there are technical hiccups.

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#6]

**Comment by jlost** [comment]
@mfldavidson @teshsopher Would there be any problems with getting these values straight from MCommunity (via OIDC) and displaying them on the "Join Info" modal?

**Comment by teshsopher** [comment]
I think that one problem with using MCommunity info would be that, in order for attendees to update their contact information, we would have to point them outside of ROHQ. Additionally, they may have a preferred contact method that isn't listed in MCommunity. 

Though, if it was reasonable, we could have a personal settings page where the student/attendee could store that information and then we could pull from that? That way, we don't have to add too much more information to the "Join Meeting" page, and could instead have an "Update your alternative contact information" link. But that's just my two cents!

**Comment by bruinc** [comment]
We could also try pulling some default information from MCommunity and allowing the attendees to override their preferred contact info if it's not what they want.

**Comment by bruinc** [comment]
Update! I've set up a new page for user preferences. The link to this page is currently at the bottom of the home page (red arrow), but James mentioned to me that it will be more suitable in the nav bar (green arrow), so I will be making that change soon.
![home_link](https://user-images.githubusercontent.com/23128544/83445711-77405b00-a41b-11ea-804c-daedc6b512b4.png)

For the preferences page, I only have a phone number so far, but I can add anything else that is needed (I can also organize it better than this):
![preferences](https://user-images.githubusercontent.com/23128544/83445786-9e972800-a41b-11ea-8f87-de4c7162c1a5.png)

And the phone number is shown in the meeting info dialog for the host to see:
![dialog](https://user-images.githubusercontent.com/23128544/83445816-ad7dda80-a41b-11ea-83c6-722072cec5a4.png)

@jlost @teshsopher Any thoughts/questions/suggestions  on things to change or add would be greatly appreciated! (But please feel free to wait until after the 1.1 release to think about this)

**Comment by jlost** [comment]
I think this looks fantastic so far! I have no problem with leaving the link where you put it if @teshsopher thinks that's a better spot. If you push your work and open a PR, I'll look it over when I have the chance.

**Comment by teshsopher** [comment]
I think this looks great! Having user preferences as its own page also sets it up for us to let users manage their notification preferences too!

If possible, I think I would place the link to the preferences (as "Manage Preferences") in the user's menu, where the red arrow is below: 
<img width="1369" alt="Screen Shot 2020-06-04 at 8 56 58 AM" src="https://user-images.githubusercontent.com/63423382/83759918-40985980-a642-11ea-9158-a32d4fb55d3d.png">

Also, where the phone number is displayed, it should have some formatting like "(555) 555-555" to make it more readable.

@jlost @mfldavidson Is there a case for adding a country selector (e.g. +1 for United States) for people with international numbers?

**Comment by jlost** [comment]
The international number selector would come for free if we used this package:
https://www.npmjs.com/package/react-phone-input-2

**Comment by mfldavidson** [comment]
Nice work @bruinc ! A few thoughts from my perspective:
1. I agree with Teshia's suggestion to put the page in the user dropdown. Maybe we want to add the Manage page there too, honestly.
2. I do think we need an international number option like the package James suggested.
3. Can we change "in which" to "by which" in the text content for the page?

**Comment by bruinc** [comment]
I moved the link to the Preferences page to the dropdown (I can move the Manage link here too if we want to make the call, as per Maggie's suggestion):
![dropdown](https://user-images.githubusercontent.com/23128544/83807711-83c5ed00-a681-11ea-96c7-82186757ce21.png)

I also got the phone number module that James found to work:
![preferences_page](https://user-images.githubusercontent.com/23128544/83808196-63e2f900-a682-11ea-87d5-20807a620ff1.png)

If I try to convert the input to a string, it omits any formatting and just yields a string of numbers, so I put this same object in the meeting info dialog and disabled any editing:
![info_dialog](https://user-images.githubusercontent.com/23128544/83807923-d1daf080-a681-11ea-8225-40d32c7c0d1e.png)
I'm still playing around with the layout of this dialog.

**Comment by teshsopher** [comment]
I'll do some quick user testing to see where users would think to put the Preferences and Manage pages (or at least see if our suggestions make sense to them), and I'll get back to you!

**Comment by teshsopher** [comment]
Just as an update:

I've done several hallway tests with potential attendees/from the attendee point of view and:

- Having the Manage Queues link in the main nav works for hosts, but there are some concerns for attendees (not a block, but something to keep in mind).
- @mfldavidson's suggestion to have the manage queues in the user menu has similar/more value than having it exposed in the main nav, and it allows for us to add a "Search queues" option (if that's something that the team thinks would be valuable).

Based on the results, I have changed my first opinion and would recommend having a "home" or "search queues" button in the main nav (though it's not necessary), and having the "Manage queue" link in the user menu, as Maggie suggested before, since this is a page geared more toward an individual, rather than the audience as a whole.

**Comment by bruinc** [comment]
So something like this?
![2020-06-29 (2)](https://user-images.githubusercontent.com/23128544/86052387-e910c200-ba24-11ea-90e1-8dfe41da7593.png)

Is the "Manage Queues" link placement good, or should it be first in the drop down? Also, do we want to leave the existing link to the Manage page at the bottom of the home page?
![image](https://user-images.githubusercontent.com/23128544/86053484-933d1980-ba26-11ea-985c-09e644794757.png)

**Comment by mfldavidson** [comment]
My opinion is:
- switch Manage Queues with Preferences in the dropdown
- leave Manage Your Own Queues on the homepage (at least for now, since users are used to finding it there)

**Comment by teshsopher** [comment]
> My opinion is:
> 
> * switch Manage Queues with Preferences in the dropdown
> * leave Manage Your Own Queues on the homepage (at least for now, since users are used to finding it there)

I agree!

**Comment by bruinc** [comment]
Merged- closing and moving to QA

**Comment by teshsopher** [comment]
Is there a way to give the users a notification (maybe an alert/banner?) that the changes have been saved? Currently, clicking save just refreshes the page and shows the new phone number.

**Comment by bruinc** [comment]
I agree that there should be a banner to signify that the changes have been saved. Along the same lines, an error banner should probably show if the validation fails (a USA number has less than 10 digits excluding the country code). @teshsopher @jlost Should I go ahead and add these banners to this branch and make a new pull request? And if so, should the issue be moved back to "In Progress"? Or would this be a new issue?

**Comment by jlost** [comment]
I think that's a great idea, but let's make it into a new issue.

**Comment by teshsopher** [comment]
Some issues with this is that:
- Users can't remove their contact info
- If the user deletes their number/clears the field, and saves it, they get an error, but the field remains blank. Additionally, the old number is still shown to hosts in the "Join Info" popup.
