### ISSUE TITLE
/manage/<queueid> errors are not apparent enough

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#68]
As we add things to the /manage/<queueid> page, it becomes harder and harder to notice errors appearing at the top of the page when the user is working at the bottom of the page, adding attendees or hosts. We may want to explore moving the place that errors appear or putting different types of errors in different places. Another possible solution is that if an error is triggered, the user is scrolled back up to the top so that they see the error. I'd like to hear @teshsopher 's thoughts about this. The second one sounds potentially too disruptive.

For example, if the user adds an attendee at the bottom that triggers an error such as invalid user, the user may not even be able to see the error unless they scroll up. This is particularly but not exclusively true on mobile.

**Comment by teshsopher** [comment]
Where possible, the errors should appear where it's relevant. So, for the example: if you're adding an attendee and they haven't logged into ROHQ, the error should appear around the "Add attendee" field. For one line error messages, this can be in line, but for multi-line messages, this should be above the field, and the field should also be outlined in red to indicate where the error happened. For errors that don't have a specific field associated with it or affect the app in general, displaying them at the top of the page is best. 

For the BlueJeans error (where there isn't a user in BlueJeans for the attendee in line), this may be best placed under the title but above the table, but I'm open to other options for this!

**Comment by mfldavidson** [comment]
I think this has been addressed by a combination of creating the #94 queue settings page and the adjustment to the #67 multiple errors. For now I think we can close this. Feel free to disagree with me and comment here?
