### ISSUE TITLE
Limit on characters in description field

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#69]
I mean...

![image](https://user-images.githubusercontent.com/31591389/83363851-bc588480-a36a-11ea-86fa-43ef7cc49f7b.png)
![image](https://user-images.githubusercontent.com/31591389/83363858-c7abb000-a36a-11ea-8a56-84355e587477.png)

**Comment by jonespm** [comment]
Yes, there should be some limits, otherwise you risk a potential security issue. Since we aren't allowing for rich text here right now. I don't know what the most appropriate limit here would be.

**Comment by jlost** [comment]
Agree -the largest description in prod currently is 846 characters. So a maximum of 1000, 1500, or 2000 at most would work.

**Comment by mfldavidson** [comment]
I think 1000 is good. Here is an example of 1000 characters in a queue description https://officehours.it.umich.edu/queue/292

**Comment by teshsopher** [comment]
I was just reviewing some of the open issues, and saw this one! I just wanted to give my two cents: I'm sure you've thought about it, but make sure you let users know, in some way, that there is a limit and let them know when they've reached it. Common practice is to have some text at the bottom right of the text box which indicates how many characters are left (and it auto-updates when users enter more or delete characters), but it's not necessarily the only way to do this.

**Comment by bruinc** [comment]
I implemented the functionality of displaying the remaining character count for the queue description that updates as the user types. Right now it's just in a paragraph element. @teshsopher Any styling advice?
![image](https://user-images.githubusercontent.com/23128544/85338429-48645480-b4b0-11ea-8570-9a4fc80138e5.png)
As a note: as soon as I shaded it, it made the change button extend too low, I'll fix that.

**Comment by teshsopher** [comment]
I would suggest having a larger text box for this, and making it a little more clear that the number is the number of characters left (so it would show "975/1000"). I would want users to be able to see all/a sizable chunk of what they've written at a glance. If someone has a long description, having it all on one line can be difficult to use.

Maybe something like this?
<img width="564" alt="image" src="https://user-images.githubusercontent.com/63423382/85452220-aa809080-b568-11ea-9eb3-2442371a8c07.png">

If this isn't technically feasible or you have a better idea, please feel free to play around with it!

**Comment by bruinc** [comment]
Here's what I have for the queue description now! You can also see it in dev.
![image](https://user-images.githubusercontent.com/23128544/85742871-9a37f500-b6d1-11ea-83f5-7a819706cc37.png)
@teshsopher Let me know if you approve or want me to tweak anything else.

**Comment by teshsopher** [comment]
Could you add just a little more space between the number and the button? After that, I think it looks great!

**Comment by bruinc** [comment]
@teshsopher Is this a good amount of space (20px)?
![image](https://user-images.githubusercontent.com/23128544/85745499-bd63a400-b6d3-11ea-9fc6-f33a0c6f4006.png)

**Comment by teshsopher** [comment]
Perfect, thank you! It looks amazing!

**Comment by teshsopher** [comment]
As I was testing I found the following:
- If the number of characters in the field is over 1000 characters, and the host tries to save, the field is no longer in the edit state. If the field had a description, it defaults to show that. I think, in this case, the field should be left in the edit state to better indicate where the error happened.
- When the host has gone over their character limit, is it possible to make the limit number a dark red and outline the field in red? (Note: If not, this isn't a major issue. Just trying to do more error prevention)

**Comment by bruinc** [comment]
@teshsopher The red accents when the description is over the character limit should be doable since the description field has already been made into a special component (a "Show Remaining" field), so this could be a new issue as well.
