### ISSUE TITLE
More useful information in queue results list

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/remote-office-hours-queue#71]
In both the manage queue page and in the search page when you search for a queue many may come back with the same or similar names since no naming restrictions are in place. The only details in the list are the name.

I'd think for the search results some additional details like possibly created date, host and possibly the number of people in the queued could be presented
![image](https://user-images.githubusercontent.com/27447/83418797-28320000-a3f2-11ea-8dc5-19625f84a5d0.png)

Additionally when managing the queue you can create multiple with the same name. There should be a column at least for created date, and possibly the id of the queue.

**Comment by mfldavidson** [comment]
We can definitely do created date and ID. Those are not as helpful as host but because you can have multiple hosts that brings in a new level of complexity...

**Comment by mfldavidson** [comment]
I'm adding this to 1.2 but for now let's not approach host

**Comment by mfldavidson** [comment]
What if we also added if it's open or not

**Comment by mfldavidson** [comment]
Responsive design is nice, good padding even when small and queue names go onto multiple lines seamlessly
