### ISSUE TITLE
Set meeting type options at the queue level

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#77]
As a queue host, I need to be able to specify the types of meetings that my queue will allow, so that my attendees can choose from BlueJeans, Zoom, and/or in-person meeting options, based on what I allow.

@teshsopher can you create a wireframe of what this could look like?

**Comment by teshsopher** [comment]
[The wireframes](https://www.sketch.com/s/88bccdc1-3ae0-4311-99a2-3dec82df2592/v/kKWM59/) are ready! I've included some quality of life changes for users in these wireframes since we've added more (and will continue to add more) features.

These changes include:
- Moved "Manage Queues" to the header/global nav (implied: Preferences under user dropdown in the header)
- Created a separate page/form-style experience for adding a queue
- Replaced the Delete Queue button with a Settings button, which lists different settings for an individual queue (Delete Queue is an option within the Settings Section).
- Moved the ability to change Queue Name and Description to the settings section
- Added pagination for the Meetings in Queue section

Let me know if you have any questions or feedback! I did my best to make UX changes that set up future planned changes, but I may have missed other factors.

**Comment by mfldavidson** [comment]
> Moved "Manage Queues" to the header/global nav (implied: Preferences under user dropdown in the header)
This makes sense to me! We want to make sure it's easy for them to find, and right now it is not.

> Created a separate page/form-style experience for adding a queue
I think this is very necessary. I see a lot of people creating queues with...weird names...that make me think that the queue creation flow right now is confusing. For example, lots have their uniqname as the queue name. One note about this--I think it might be clearer to literally SHOW that they have been added as a host automatically the way they can see it in the Manage Queue page now, rather than telling them that, on the Manage Hosts part of the queue creation flow. What do you think?

> Replaced the Delete Queue button with a Settings button, which lists different settings for an individual queue (Delete Queue is an option within the Settings Section).
Yesss I love it!!! This stuff def belongs in a settings area, particularly Delete, as users definitely delete when they don't mean to. We have to make it harder! I also quite like the language you use throughout.

> Added pagination for the Meetings in Queue section
We may want to look at using tablesorter which would allow pagination, filtering, sorting, etc. We use it in Student Explorer and people love it. https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v4.html

I think we need to make these separate issues. I'll wait until @jlost is back to discuss though.

**Comment by bruinc** [comment]
@mfldavidson @teshsopher The Manage Queue Settings Page (#94) and Add Queue Workflow (#95) issues address all of the host-side UI changes, but how do we want this to present to the attendee? The attendee should probably be forced to choose a meeting type when they try to join a queue if there are multiple possible meeting types, but should this be changeable on the "Joined Queue" page as well (i.e. should the attendee be able to change the meeting type without losing their place in line)?

**Comment by teshsopher** [comment]
I have [a mockup for the Join Queue page](https://www.sketch.com/s/1c11c19c-c109-46c0-a541-b1b9b18b2d5f/a/WveRW0). I agree that the attendee should be forced to choose a meeting type when they join the queue, and I used an asterisk to visually indicate that the field is required. I'm currently doing user testing with it, and most users (so far) have understood what actions they need to take when they reach this page. 

As far as changing the meeting type in line, I'm inclined to say that users should be able to change this. However, I don't know if this poses technical problems, but, on the UX side, one potential challenge is what does the host experience if they have already joined the meeting/are ready to join when the attendee has changed the meeting type. I don't know what would happen on the backend, so I'm not sure how to mockup/suggest options for what the host would see.

**Comment by bruinc** [comment]
@teshsopher What if we allow the attendee to change the meeting type as much as they want until a host is assigned to their meeting?

**Comment by teshsopher** [comment]
@bruinc That's a great idea! My only concern with that is hosts can be assigned at any time and not just when a host joins a meeting, but if that isn't a major concern (I'm inclined to say it isn't, but it may be something we revisit later), then we can go forward with that solution. I'll update the mockup I linked above with what I think this should look like later today!

**Comment by bruinc** [comment]
@teshsopher Since the meeting type is a required field for a meeting, should we also force the host to choose an initial meeting type when they manually add an attendee? Maybe something similar to this (excuse my choppy copy/paste):
![image](https://user-images.githubusercontent.com/23128544/87336759-5d149500-c510-11ea-8a7a-92eccd62f4ae.png)

**Comment by teshsopher** [comment]
@bruinc Yes, hosts should be forced to choose a meeting type, and using something similar to what you've laid out would work for this!

**Comment by teshsopher** [comment]
@jlost A few thoughts: If hosts are able to change what meeting types are available while the queue is open/has attendees, then an error or message should pop up for attendees that are in line to select a meeting type from the new available options.

Additionally, if a host has already started a meeting, should the meeting type for that meeting should not be able to be changed? I would also wonder if we should prevent meeting type changes if an attendee is also in a meeting.

**Comment by teshsopher** [comment]
Also, is it possible to require at least one option be selected and have one option selected by default on queue creation (I would recommend BlueJeans be the default option, but I'm open to other opinions!).

**Comment by jlost** [comment]
In the interest of getting this out the door, I made it so an error message is displayed if you try to disallow a meeting type for which there is currently a meeting:
>Allowed Meeting Types: You can't disallow this meeting type until the following meetings that use it have been removed from the queue: James Ostrander (jlost), John Doe (jdoe), Et Cetera (etc)

Any comments or changes for the text?
I think we should spin a better solution (allow the change but prompt conflicting attendees to change) off into a separate issue, because it's better UX, but also significantly more work to implement.

**Comment by mfldavidson** [comment]
Oh I'm sorry I said I'd get you that text and then I didn't. But I think that is actually a pretty good permanent solution, functionalitywise. We could create a new issue for the alternative idea but like you said, lots of work to implement, and I'd like to understand if it's really needed before we try to do it.

If it's possible to list the meetings, I love that idea. I like your text as well. Nice work 👍

**Comment by teshsopher** [comment]
I agree that not allowing hosts to disallow a meeting type when there's a meeting for that type is a good permanent solution. The text is also good!

**Comment by teshsopher** [comment]
@jlost I found two bugs:
- If a queue only lists "In person" as a meeting type, when the attendee joins the queue, the "Meeting via" field shows BlueJeans. Attendees are also unable to change the meeting type.
- When the attendee changes their meeting type from "BlueJeans" to "In person," the host's view continues to show the "Start Meeting" button as if the attendee were meeting via BlueJeans

**Comment by jlost** [comment]
Thanks @teshsopher, those were good finds and potential showstoppers. I believe I've fixed both of these issues - check it out in dev.

**Comment by teshsopher** [comment]
@jlost It all looks good to me now!

QA tested and working in dev on 8/17
