### ISSUE TITLE
Change international number link

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#83]
On both the host side and attendee side we link to https://www.bluejeans.com/numbers

Change to https://www.bluejeans.com/premium-numbers per John Simpkins 6/11/2020

**Comment by mfldavidson** [comment]
@ksofa2 unless I missed something, this is not done (I consider "done" = "in dev and tested" and it is not currently in dev nor has it been tested) so I am moving it back

**Comment by bruinc** [comment]
@jlost Can I go ahead and merge this into dev?

**Comment by jlost** [comment]
Sure thing!

**Comment by bruinc** [comment]
Successfully merged into dev, and the links go to the correct premium numbers webpage when testing in dev.

**Comment by teshsopher** [comment]
Tested and working in dev on 7/21
