### ISSUE TITLE
Configurable email subject prefix for error emails

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#88]
So we can tell apart emails from dev and prod easier. Ref https://github.com/tl-its-umich-edu/student_explorer/pull/193 and https://github.com/tl-its-umich-edu/student_explorer/blob/2d5445a7b5ec0f7da8e634d7676c67a464ca4404/student_explorer/settings.py#L163 for how implemented in Student Explorer (we set it to "PROD Student Explorer", "TEST Student Explorer" etc)

**Comment by mfldavidson** [comment]
We now know that what you tried worked, right @jlost ?

**Comment by mfldavidson** [comment]
Not sure why this is still open, this was done in 1.2

**Comment by jlost** [comment]
Yes, this was done in #89.
