### ISSUE TITLE
Fix Modified Migration (0013)

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#90]
I overlooked a bug when reviewing #47 - it looks like when the "agenda" migrations were squashed, they were squashed one level too deep, which merged them into `0013_add_queue_status.py`. Migrations that have been released (queue status was released in v1.1) shouldn't be modified, because it puts databases that have already applied the modified migrations out of sync with the migration state in a way that is very difficult to reconcile.  For instance, if I applied the v1.2 migrations in prod, it wouldn't create the agenda field because 0013 is already tracked as having been applied, so there would be an error whenever Django tried to do anything with the agenda field. 

In the end, `0013` should be as it was in v1.1, adding "agenda" should be one more migration (`0014`), and ideally the other migrations that we've added since then would be separate and continue on as `0015`, etc. It might be necessary to manually change the migrations names and dependencies to make this work.

**Comment by mfldavidson** [comment]
I think this got moved back to QA just by automation and shouldn't have, I assume y'all have confirmed it is done so I will move it. Nothing to do to test.
